load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "timeconst_lib",
    srcs = ["main.go"],
    importpath = "linux.bzl/internal/cmd/timeconst",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "timeconst",
    embed = [":timeconst_lib"],
    visibility = ["//:__subpackages__"],
)
