// Copyright The Monogon Project Authors.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	config := flag.String("config", "", "Resolved Linux .config input")
	out := flag.String("out", "", "Generated timeconst.h output")
	flag.Parse()

	if *config == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "-config and -out are required")
		os.Exit(2)
	}
	if err := run(*config, *out); err != nil {
		fmt.Fprintf(os.Stderr, "timeconst: %v\n", err)
		os.Exit(1)
	}
}

func run(configPath, outPath string) error {
	hz, err := configHZ(configPath)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(timeconstHeader(hz)), 0o644)
}

func configHZ(path string) (uint64, error) {
	file, err := os.Open(path)
	if err != nil {
		return 0, err
	}
	defer file.Close()
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		key, value, ok := strings.Cut(strings.TrimSpace(scanner.Text()), "=")
		if !ok || key != "CONFIG_HZ" {
			continue
		}
		hz, err := strconv.ParseUint(value, 10, 64)
		if err != nil {
			return 0, err
		}
		if hz < 2 {
			return 0, fmt.Errorf("CONFIG_HZ=%d is not supported", hz)
		}
		return hz, nil
	}
	if err := scanner.Err(); err != nil {
		return 0, err
	}
	return 0, fmt.Errorf("CONFIG_HZ not found")
}

func timeconstHeader(hz uint64) string {
	var out strings.Builder
	fmt.Fprintln(&out, "/* Automatically generated by Bazel timeconst. */")
	fmt.Fprintf(&out, "/* Time conversion constants for HZ == %d */\n\n", hz)
	fmt.Fprintln(&out, "#ifndef KERNEL_TIMECONST_H")
	fmt.Fprintln(&out, "#define KERNEL_TIMECONST_H")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "#include <linux/param.h>")
	fmt.Fprintln(&out, "#include <linux/types.h>")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "#if HZ != %d\n", hz)
	fmt.Fprintln(&out, "#error \"include/generated/timeconst.h has the wrong HZ value!\"")
	fmt.Fprintln(&out, "#endif")
	fmt.Fprintln(&out)
	writeConversion(&out, "HZ_TO_MSEC", 1000, hz)
	writeConversion(&out, "MSEC_TO_HZ", hz, 1000)
	writeFraction(&out, "HZ_TO_MSEC", 1000, hz)
	writeFraction(&out, "MSEC_TO_HZ", hz, 1000)
	fmt.Fprintln(&out)
	writeConversion(&out, "HZ_TO_USEC", 1000000, hz)
	writeConversion(&out, "USEC_TO_HZ", hz, 1000000)
	writeFraction(&out, "HZ_TO_USEC", 1000000, hz)
	writeFraction(&out, "USEC_TO_HZ", hz, 1000000)
	writeFraction(&out, "HZ_TO_NSEC", 1000000000, hz)
	writeFraction(&out, "NSEC_TO_HZ", hz, 1000000000)
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "#endif /* KERNEL_TIMECONST_H */")
	return out.String()
}

func writeConversion(out *strings.Builder, name string, n, d uint64) {
	shift := fmuls(32, n, d)
	fmt.Fprintf(out, "#define %s_MUL32\tU64_C(0x%X)\n", name, fmul(shift, n, d))
	fmt.Fprintf(out, "#define %s_ADJ32\tU64_C(0x%X)\n", name, fadj(shift, n, d))
	fmt.Fprintf(out, "#define %s_SHR32\t%d\n", name, shift)
}

func writeFraction(out *strings.Builder, name string, n, d uint64) {
	divisor := gcd(n, d)
	fmt.Fprintf(out, "#define %s_NUM\t\t%d\n", name, n/divisor)
	fmt.Fprintf(out, "#define %s_DEN\t\t%d\n", name, d/divisor)
}

func gcd(a, b uint64) uint64 {
	for b != 0 {
		a, b = b, a%b
	}
	return a
}

func fmul(bits uint, n, d uint64) uint64 {
	return ((uint64(1)<<bits)*n + d - 1) / d
}

func fadj(bits uint, n, d uint64) uint64 {
	d = d / gcd(n, d)
	return ((uint64(1) << bits) * (d - 1)) / d
}

func fmuls(bits uint, n, d uint64) uint {
	for shift := uint(0); ; shift++ {
		if fmul(shift, n, d) >= uint64(1)<<(bits-1) {
			return shift
		}
	}
}
