package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var oidRE = regexp.MustCompile(`\s+OID_([a-zA-z][a-zA-Z0-9_]+),\s+/\*\s+([012][.0-9]*)\s+\*/`)

type oidEntry struct {
	name    string
	oid     string
	index   int
	encoded []int
	hash    int
}

func main() {
	in := flag.String("in", "", "include/linux/oid_registry.h input")
	out := flag.String("out", "", "Generated oid_registry_data.c output")
	script := flag.String("script", "lib/build_OID_registry", "Upstream script name to mention in generated comment")
	flag.Parse()

	if *in == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "-in and -out are required")
		os.Exit(2)
	}
	if err := run(*in, *out, *script); err != nil {
		fmt.Fprintf(os.Stderr, "oidregistry: %v\n", err)
		os.Exit(1)
	}
}

func run(in, out, script string) error {
	entries, err := parseEntries(in)
	if err != nil {
		return err
	}
	totalLength := 0
	for i := range entries {
		entries[i].index = totalLength
		entries[i].encoded, err = encodeOID(entries[i].oid)
		if err != nil {
			return fmt.Errorf("%s: %w", entries[i].name, err)
		}
		totalLength += len(entries[i].encoded)
		entries[i].hash = oidHash(entries[i].encoded)
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	output, err := os.Create(out)
	if err != nil {
		return err
	}
	defer output.Close()

	writeOIDRegistry(output, entries, totalLength, script)
	return nil
}

func parseEntries(in string) ([]oidEntry, error) {
	input, err := os.Open(in)
	if err != nil {
		return nil, err
	}
	defer input.Close()

	var entries []oidEntry
	scanner := bufio.NewScanner(input)
	for scanner.Scan() {
		matches := oidRE.FindStringSubmatch(scanner.Text())
		if matches == nil {
			continue
		}
		entries = append(entries, oidEntry{name: matches[1], oid: matches[2]})
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("%s: %w", in, err)
	}
	return entries, nil
}

func encodeOID(oid string) ([]int, error) {
	parts := strings.Split(oid, ".")
	if len(parts) < 2 {
		return nil, fmt.Errorf("OID has fewer than two components: %q", oid)
	}
	components := make([]uint64, 0, len(parts))
	for _, part := range parts {
		component, err := strconv.ParseUint(part, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("invalid component %q: %w", part, err)
		}
		components = append(components, component)
	}

	octets := []int{int(components[0]*40 + components[1])}
	for _, component := range components[2:] {
		shift := 0
		if component != 0 {
			shift = bitLength(component) / 7
		}
		for ; shift > 0; shift-- {
			octets = append(octets, int((component>>uint(shift*7))&0x7f)|0x80)
		}
		octets = append(octets, int(component&0x7f))
	}
	return octets, nil
}

func bitLength(value uint64) int {
	length := 0
	for value != 0 {
		length++
		value >>= 1
	}
	return length - 1
}

func oidHash(octets []int) int {
	hash := len(octets) - 1
	for _, octet := range octets {
		hash += octet * 33
	}
	hash = (hash >> 24) ^ (hash >> 16) ^ (hash >> 8) ^ hash
	return hash & 0xff
}

func writeOIDRegistry(output *os.File, entries []oidEntry, totalLength int, script string) {
	fmt.Fprint(output, "/*\n")
	fmt.Fprintf(output, " * Automatically generated by %s.  Do not edit\n", script)
	fmt.Fprint(output, " */\n")

	fmt.Fprint(output, "\n")
	if totalLength <= 255 {
		fmt.Fprint(output, "static const unsigned char oid_index[OID__NR + 1] = {\n")
	} else {
		fmt.Fprint(output, "static const unsigned short oid_index[OID__NR + 1] = {\n")
	}
	for _, entry := range entries {
		fmt.Fprintf(output, "\t[OID_%s] = %d,\n", entry.name, entry.index)
	}
	fmt.Fprintf(output, "\t[OID__NR] = %d\n", totalLength)
	fmt.Fprint(output, "};\n")

	fmt.Fprint(output, "\n")
	fmt.Fprintf(output, "static const unsigned char oid_data[%d] = {\n", totalLength)
	for _, entry := range entries {
		fmt.Fprint(output, "\t")
		for _, octet := range entry.encoded {
			fmt.Fprintf(output, "%d, ", octet)
		}
		fmt.Fprintf(output, "\t// %s\n", entry.name)
	}
	fmt.Fprint(output, "};\n")

	search := append([]oidEntry(nil), entries...)
	sort.SliceStable(search, func(i, j int) bool {
		a := search[i]
		b := search[j]
		if a.hash != b.hash {
			return a.hash < b.hash
		}
		if len(a.encoded) != len(b.encoded) {
			return len(a.encoded) < len(b.encoded)
		}
		for k := len(a.encoded) - 1; k >= 0; k-- {
			if a.encoded[k] != b.encoded[k] {
				return a.encoded[k] < b.encoded[k]
			}
		}
		return false
	})

	fmt.Fprint(output, "\n")
	fmt.Fprint(output, "static const struct {\n")
	fmt.Fprint(output, "\tunsigned char hash;\n")
	if len(entries)-1 <= 255 {
		fmt.Fprint(output, "\tenum OID oid : 8;\n")
	} else {
		fmt.Fprint(output, "\tenum OID oid : 16;\n")
	}
	fmt.Fprint(output, "} oid_search_table[OID__NR] = {\n")
	for i, entry := range search {
		fmt.Fprintf(output, "\t[%3d] = { %3d, OID_%-35s }, // ", i, entry.hash, entry.name)
		for _, octet := range entry.encoded {
			fmt.Fprintf(output, "%02x", octet)
		}
		fmt.Fprint(output, "\n")
	}
	fmt.Fprint(output, "};\n")
}
