package kconfig

import (
	"bytes"
	"fmt"
	"sort"

	bzl "github.com/bazelbuild/buildtools/build"

	"github.com/hermeticbuild/linux.bzl/internal/kconfig/buildgen"
)

// MergeBuildFiles combines generated BUILD files with compatible package()
// declarations, merged load() statements, and optional exports_files entries.
func MergeBuildFiles(filename string, exportedFiles []string, inputs ...[]byte) ([]byte, error) {
	loads := map[string]map[string]bool{}
	var packageStmt bzl.Expr
	var packageText string
	var stmts []bzl.Expr

	for i, input := range inputs {
		file, err := bzl.ParseBuild(fmt.Sprintf("%s.%d", filename, i), input)
		if err != nil {
			return nil, err
		}
		for _, stmt := range file.Stmt {
			switch x := stmt.(type) {
			case *bzl.LoadStmt:
				module := x.Module.Value
				if loads[module] == nil {
					loads[module] = map[string]bool{}
				}
				for i, from := range x.From {
					if i >= len(x.To) || x.To[i].Name != from.Name {
						return nil, fmt.Errorf("cannot merge aliased load from %s", module)
					}
					loads[module][from.Name] = true
				}
			case *bzl.CallExpr:
				if ident, ok := x.X.(*bzl.Ident); ok && ident.Name == "package" {
					formatted := string(bzl.FormatString(x))
					if packageStmt == nil {
						packageStmt = x
						packageText = formatted
					} else if formatted != packageText {
						return nil, fmt.Errorf("conflicting package() declarations")
					}
					continue
				}
				stmts = append(stmts, stmt)
			default:
				stmts = append(stmts, stmt)
			}
		}
	}

	var out bzl.File
	out.Type = bzl.TypeBuild
	for _, module := range sortedLoadModules(loads) {
		out.Stmt = append(out.Stmt, buildgen.LoadStmt(module, sortedKeys(loads[module])...))
	}
	if packageStmt != nil {
		out.Stmt = append(out.Stmt, packageStmt)
	}
	if len(exportedFiles) != 0 {
		out.Stmt = append(out.Stmt, exportsFilesStmt(exportedFiles))
	}
	out.Stmt = append(out.Stmt, stmts...)

	var data bytes.Buffer
	data.WriteString("# Generated by kconfig_parse compact backend. Do not edit.\n\n")
	formatted := bzl.Format(&out)
	formatted = bytes.ReplaceAll(formatted, []byte("\n# Generated by kconfig_parse compact backend. Do not edit.\n\n"), []byte("\n"))
	data.Write(formatted)
	return data.Bytes(), nil
}

func exportsFilesStmt(files []string) bzl.Expr {
	return &bzl.CallExpr{
		X: &bzl.Ident{Name: "exports_files"},
		List: []bzl.Expr{
			buildgen.Expr(files),
		},
	}
}

func sortedKeys(values map[string]bool) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedLoadModules(values map[string]map[string]bool) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
