package kconfig

import (
	"io"
	"maps"
	"os"
	"slices"
	"strconv"
)

// Lookahead spends only the existing entered-file inventory's remaining work
// and name budgets. Byte reads (also on cache hits), directive visits and lookup
// attempts are additional charged work. None of these counters is CPU time.
func (b *configDependencyOpenedHeaderHintBudget) chargeLookahead(work int) bool {
	if b.disabled || work < 0 || work > 65536-b.work {
		return false
	}
	b.work += work
	return true
}

// Candidate lookup has no live scanner state, trace, demand collection or read
// receipt. The callbacks below resolve immutable current input ownership and
// generated bytes; their caches do not certify that a consumer read an output.
// In particular, never clear the real scanner's first failure to do lookahead.
func (s *configDependencyClosureScanner) compilerHintLookupView() *configDependencyClosureScanner {
	generatedText := maps.Clone(s.generatedText)
	if generatedText == nil {
		generatedText = map[string]configDependencyGeneratedText{}
	}
	return &configDependencyClosureScanner{
		profile: s.profile, physicalFiles: s.physicalFiles,
		generated: s.generated, generatedText: generatedText,
		resolveGeneratedText: s.resolveGeneratedText, lookupWorkingInput: s.lookupWorkingInput,
		preconfigured:    s.preconfigured,
		quoteDirectories: s.quoteDirectories, includeDirectories: s.includeDirectories,
		systemDirectories: s.systemDirectories, afterDirectories: s.afterDirectories,
	}
}

func compilerHintLookaheadFileKey(file configDependencyScanFile) string {
	// Equal physical bytes reached under another logical alias can have a
	// different quoted-include parent. Do not merge those lookup contexts.
	return file.identity() + "\x00" + file.logical + "\x00" + strconv.FormatBool(file.source)
}

func (s *configDependencyClosureScanner) compilerHintCandidateSyntax(
	file configDependencyScanFile, budget *configDependencyOpenedHeaderHintBudget,
) (configDependencyConditionalSyntax, bool) {
	if file.identity() == "" || file.configProjection || file.macroTable || budget.disabled {
		return configDependencyConditionalSyntax{}, false
	}
	key := s.conditionalSyntaxCacheKey(file)
	syntax, cached := s.conditionalSyntax[key]
	// Reserve the read plus at least one work unit per source byte for the
	// inventory before parsing. An oversized candidate cannot erase the hints
	// already admitted from entered files or smaller complete candidates.
	maximumBytes := min(configDependencyCompilerGuardHintsMaximumBytes, (65536-budget.work)/2)
	if maximumBytes <= 0 {
		return configDependencyConditionalSyntax{}, false
	}
	if cached && syntax.compilerTokenInventoryReady && syntax.compilerGuardContentID != "" {
		if syntax.sourceBytes < 0 || syntax.sourceBytes > maximumBytes ||
			!budget.chargeLookahead(syntax.sourceBytes) {
			return configDependencyConditionalSyntax{}, false
		}
	} else {
		contents, readWork, ok := readCompilerHintCandidate(file, maximumBytes)
		if !budget.chargeLookahead(readWork) || !ok {
			return configDependencyConditionalSyntax{}, false
		}
		syntax = s.cacheConditionalSyntaxForContents(file, contents, nil)
	}
	if syntax.reason != "" || syntax.conditionalProgram.reason != "" || !syntax.conditionalProgram.callCoverage {
		return configDependencyConditionalSyntax{}, false
	}
	if !syntax.lookaheadTokenInventoryReady {
		// Unlike entered files, a candidate has no higher-priority conditional
		// observer. Its operand names may therefore be weak hints too. Intrinsic
		// calls are never invented here, nor are computed include paths followed.
		syntax.lookaheadTokenInventory = configDependencyTokenHintInventoryForProgram(syntax.sourceBytes, syntax.conditionalProgram, true)
		syntax.lookaheadTokenInventoryReady = true
		s.conditionalSyntax[key] = syntax
	}
	return syntax, !syntax.lookaheadTokenInventory.hints.truncated
}

func readCompilerHintCandidate(file configDependencyScanFile, maximumBytes int) ([]byte, int, bool) {
	if file.exactIdentity != "" {
		if len(file.exactContents) > maximumBytes {
			return nil, 0, false
		}
		return []byte(file.exactContents), len(file.exactContents), true
	}
	// Stat before opening so an optional candidate cannot block on a FIFO or
	// read an oversized file. Recheck the opened descriptor and limit its read.
	info, err := os.Stat(file.physical)
	if err != nil || !info.Mode().IsRegular() || info.Size() > int64(maximumBytes) {
		return nil, 0, false
	}
	input, err := os.Open(file.physical)
	if err != nil {
		return nil, 0, false
	}
	defer input.Close()
	info, err = input.Stat()
	if err != nil || !info.Mode().IsRegular() || info.Size() > int64(maximumBytes) {
		return nil, 0, false
	}
	contents, err := io.ReadAll(io.LimitReader(input, int64(maximumBytes)+1))
	return contents, len(contents), err == nil && len(contents) <= maximumBytes && int64(len(contents)) == info.Size()
}

func (s *configDependencyClosureScanner) emitCompilerLiteralIncludeHintLookahead(
	probe configDependencyCompilerPredefineProbe,
	observe func(configDependencyCompilerPredefineProbe, configDependencyScanFile, configDependencyCompilerGuardHints, string),
	budget *configDependencyOpenedHeaderHintBudget,
) {
	if budget.disabled || s.compilerGuardFilesTruncated || len(s.compilerGuardFiles) > 4096 {
		return
	}
	type candidate struct {
		file    configDependencyScanFile
		program configDependencyConditionalProgram
	}
	var queue []candidate
	seen := map[string]bool{}
	for _, identity := range slices.Sorted(maps.Keys(s.compilerGuardFiles)) {
		file := s.compilerGuardFiles[identity]
		syntax, found := s.conditionalSyntax[s.conditionalSyntaxCacheKey(file)]
		if !found || !syntax.compilerTokenInventoryReady || syntax.compilerTokenInventory.hints.truncated ||
			syntax.conditionalProgram.reason != "" || !syntax.conditionalProgram.callCoverage {
			continue
		}
		seen[compilerHintLookaheadFileKey(file)] = true
		queue = append(queue, candidate{file, syntax.conditionalProgram})
	}
	lookup := s.compilerHintLookupView()
	for index := 0; index < len(queue); index++ {
		current := queue[index]
		for _, entry := range current.program.directives {
			if !budget.chargeLookahead(1) {
				return
			}
			if entry.directive != "include" && entry.directive != "import" {
				continue
			}
			lookupWork := len(entry.rest) + 10 + len(s.quoteDirectories) + len(s.includeDirectories) + len(s.systemDirectories) + len(s.afterDirectories)
			if !budget.chargeLookahead(lookupWork) {
				return
			}
			// Parse just this normalized operand, not the surrounding conditional
			// or macro definitions. Unsupported operands provide no candidate.
			includes, reason := configDependencyLiteralIncludes([]byte("#include " + entry.rest))
			if reason != "" || len(includes) != 1 {
				continue
			}
			lookup.opaqueReason = ""
			lookup.resolvedGeneratedFiles = nil
			file, found := lookup.resolveIncludeFile(current.file, includes[0])
			if !found || lookup.opaqueReason != "" {
				continue
			}
			key := compilerHintLookaheadFileKey(file)
			if seen[key] {
				continue
			}
			if len(seen) >= 4096 {
				return
			}
			seen[key] = true
			syntax, valid := s.compilerHintCandidateSyntax(file, budget)
			if !valid {
				continue
			}
			inventory := syntax.lookaheadTokenInventory
			var names []string
			for _, name := range inventory.hints.names {
				initial, valid := s.compilerIntrinsicInitialSnapshot.lookup(name)
				if !valid || initial.definition != configDependencyMacroUnknown {
					continue
				}
				if _, measured := s.compilerGuardInitialDefinitions[name]; !measured {
					names = append(names, name)
				}
			}
			inventory.hints.names = names // Detached; cached inventory is immutable.
			names, truncated := budget.add(inventory)
			if truncated {
				return
			}
			if len(names) != 0 {
				observe(probe, file, configDependencyCompilerGuardHints{names: names, optionalTokenHints: true, literalIncludeHints: true}, syntax.compilerGuardContentID)
			}
			queue = append(queue, candidate{file, syntax.conditionalProgram})
		}
	}
}
