package kconfig

import (
	"crypto/sha256"
	"maps"
	"slices"
)

// Ordinary header effects are analysis-local. Unlike the syntax cache, these
// entries either reuse an identical immutable macro snapshot or validate every
// entry cell consumed by the recorded execution. They never reuse another
// translation unit's scanner wholesale or infer include bindings from the
// selected header's path alone.
type configDependencyHeaderCache struct {
	entries                                      map[configDependencyHeaderCacheKey][]configDependencyHeaderCacheEntry
	entryCount, records, bytes                   int
	maximumEntries, maximumRecords, maximumBytes int
	maximumVariants                              int
	hits, misses, stores, rejected               int
	exactHits, specializedHits                   int
	requirementMismatches, replayMismatches      int
	rejectedEntries, rejectedVariants            int
	rejectedRecords, rejectedBytes               int
	rejectedTrace, rejectedWholeNamespace        int
	rejectedInexact, rejectedMacro               int
	captureAttempts                              int
	admissionStopped                             bool
	admissionStopReason                          configDependencyHeaderRejection
}

type configDependencyHeaderCacheKey struct {
	file                      configDependencyScanFile
	profile, language, search string
	autoconf                  [sha256.Size]byte
}

type configDependencyHeaderCacheEntry struct {
	effect         configDependencyMacroEffect
	specialization configDependencyMacroSpecialization
	events         []configDependencyHeaderEvent
}

type configDependencyHeaderRejection uint8

const (
	configDependencyHeaderRejectTrace configDependencyHeaderRejection = iota
	configDependencyHeaderRejectEntries
	configDependencyHeaderRejectVariants
	configDependencyHeaderRejectRecords
	configDependencyHeaderRejectBytes
	configDependencyHeaderRejectWholeNamespace
	configDependencyHeaderRejectInexact
	configDependencyHeaderRejectMacro
)

func (c *configDependencyHeaderCache) reject(reason configDependencyHeaderRejection) {
	if !c.admissionStopped && c.entryCount != 0 &&
		(reason == configDependencyHeaderRejectRecords || reason == configDependencyHeaderRejectBytes) {
		// Stop spending trace work on a populated cache that cannot accommodate
		// another attempted entry. Keep all existing entries usable. An empty
		// cache deliberately keeps trying: one oversized header must not prevent
		// smaller later headers from establishing useful entries.
		c.admissionStopped = true
		c.admissionStopReason = reason
	}
	c.rejected++
	switch reason {
	case configDependencyHeaderRejectEntries:
		c.rejectedEntries++
	case configDependencyHeaderRejectVariants:
		c.rejectedVariants++
	case configDependencyHeaderRejectRecords:
		c.rejectedRecords++
	case configDependencyHeaderRejectBytes:
		c.rejectedBytes++
	case configDependencyHeaderRejectWholeNamespace:
		c.rejectedWholeNamespace++
	case configDependencyHeaderRejectInexact:
		c.rejectedInexact++
	case configDependencyHeaderRejectMacro:
		c.rejectedMacro++
	default:
		c.rejectedTrace++
	}
}

func (c *configDependencyHeaderCache) admissionLimit(variants int) (configDependencyHeaderRejection, bool) {
	switch {
	case c.admissionStopped:
		return c.admissionStopReason, true
	case c.entryCount >= c.maximumEntries:
		return configDependencyHeaderRejectEntries, true
	case variants >= c.maximumVariants:
		return configDependencyHeaderRejectVariants, true
	case c.records >= c.maximumRecords:
		return configDependencyHeaderRejectRecords, true
	case c.bytes >= c.maximumBytes:
		return configDependencyHeaderRejectBytes, true
	default:
		return configDependencyHeaderRejectTrace, false
	}
}

type configDependencyHeaderEventKind uint8

const (
	configDependencyHeaderEnter configDependencyHeaderEventKind = iota
	configDependencyHeaderResolve
	configDependencyHeaderParsed
	configDependencyHeaderGuard
)

// Events preserve preprocessing order. In particular queueConditional and the
// parsed-summary merge must still run on a hit: earlier TU inputs can change
// alias checks, pending membership, and already accumulated dependency facts.
type configDependencyHeaderEvent struct {
	kind      configDependencyHeaderEventKind
	file      configDependencyScanFile
	including configDependencyScanFile
	include   configDependencyLiteralInclude
	parsed    configDependencyParsedFile
	guard     string
	binding   configDependencyHeaderBinding
}

// A physical snapshot can stand in for generated bytes during planning. Keep
// its concrete producer/source binding as well as the selected scan file; a
// matching snapshot pathname alone does not establish the same provenance.
type configDependencyHeaderBinding struct {
	entry         ActionPlanInputSetEntry
	source        ActionPlanSource
	projection    string
	found, config bool
}

func (s *configDependencyClosureScanner) headerBinding(file configDependencyScanFile) (configDependencyHeaderBinding, bool) {
	if file.source {
		return configDependencyHeaderBinding{}, true
	}
	bound, found := s.boundWorkingInput(file.logical)
	if s.opaqueReason != "" {
		return configDependencyHeaderBinding{}, false
	}
	if !found && s.generated[file.logical] && file.exactIdentity == "" && !file.configProjection {
		return configDependencyHeaderBinding{}, false
	}
	return configDependencyHeaderBinding{
		entry: bound.entry, source: bound.source, projection: bound.projection, found: found, config: bound.config,
	}, true
}

func (s *configDependencyClosureScanner) recordHeaderResolution(including configDependencyScanFile, include configDependencyLiteralInclude, file configDependencyScanFile) {
	trace := s.headerTrace
	if trace == nil || trace.invalid {
		return
	}
	probe := *s
	binding, valid := probe.headerBinding(file)
	if !valid {
		trace.invalid = true
		trace.rejection = configDependencyHeaderRejectTrace
		trace.events = nil
		return
	}
	trace.record(configDependencyHeaderEvent{
		kind: configDependencyHeaderResolve, file: file, including: including, include: include, binding: binding,
	})
}

type configDependencyHeaderTrace struct {
	events                       []configDependencyHeaderEvent
	ancestors                    map[string]*configDependencyConditionalActiveFile
	records, bytes               int
	maximumRecords, maximumBytes int
	invalid                      bool
	resolutionsOnly              bool
	rejection                    configDependencyHeaderRejection
}

func newConfigDependencyForcedHeaderResolutionTrace() *configDependencyHeaderTrace {
	return &configDependencyHeaderTrace{
		resolutionsOnly: true, maximumRecords: 1 << 18, maximumBytes: 32 << 20,
	}
}

func (c *configDependencyHeaderCache) initialize() {
	if c.entries == nil {
		c.entries = map[configDependencyHeaderCacheKey][]configDependencyHeaderCacheEntry{}
	}
	if c.maximumEntries == 0 {
		c.maximumEntries = 256
	}
	if c.maximumRecords == 0 {
		c.maximumRecords = 1 << 18
	}
	if c.maximumBytes == 0 {
		c.maximumBytes = 32 << 20
	}
	if c.maximumVariants == 0 {
		// Bound failed dependency checks for a header with many entry states.
		c.maximumVariants = 16
	}
}

// Limits cover retained events, finite macro effects, and counted string
// payload, not total heap: immutable snapshots also retain shared trees.
func (e configDependencyHeaderEvent) retainedSize() (records, bytes int) {
	records = 1
	fileSize := func(f configDependencyScanFile) int {
		return len(f.logical) + len(f.physical) + len(f.exactContents) + len(f.exactIdentity)
	}
	bytes = fileSize(e.file) + fileSize(e.including) + len(e.include.name) + len(e.guard)
	bytes += len(e.binding.entry.Target.Tree) + len(e.binding.entry.Target.Path) + len(e.binding.entry.SourceID) + len(e.binding.entry.ProducerID)
	bytes += len(e.binding.source.ID) + len(e.binding.source.Namespace) + len(e.binding.source.Path) + len(e.binding.projection)
	for _, values := range [][]string{e.parsed.symbols, e.parsed.macroRoots, e.parsed.macroUndefinitions} {
		records += len(values)
		for _, value := range values {
			bytes += len(value)
		}
	}
	records += len(e.parsed.includes) + len(e.parsed.macroDefinitions)
	for _, include := range e.parsed.includes {
		bytes += len(include.name)
	}
	for _, definition := range e.parsed.macroDefinitions {
		bytes += len(definition.name)
		for _, values := range [][]string{definition.identifiers, definition.safeTokenPastePrefixes} {
			records += len(values)
			for _, value := range values {
				bytes += len(value)
			}
		}
	}
	return records, bytes
}

func (t *configDependencyHeaderTrace) record(event configDependencyHeaderEvent) {
	if t == nil || t.invalid {
		return
	}
	if t.resolutionsOnly && event.kind != configDependencyHeaderResolve {
		return
	}
	if event.kind == configDependencyHeaderEnter && t.ancestors[event.file.identity()] != nil {
		// Recursion internal to this closure is deterministic, but reaching the
		// active TU depends on state outside the cached invocation boundary.
		t.invalid = true
		t.rejection = configDependencyHeaderRejectTrace
		t.events = nil
		return
	}
	records, bytes := event.retainedSize()
	if records > t.maximumRecords-t.records {
		t.invalid = true
		t.rejection = configDependencyHeaderRejectRecords
		t.events = nil
		return
	}
	if bytes > t.maximumBytes-t.bytes {
		t.invalid = true
		t.rejection = configDependencyHeaderRejectBytes
		t.events = nil
		return
	}
	if event.kind == configDependencyHeaderParsed {
		event.parsed = cloneConfigDependencyParsedFile(event.parsed)
		event.parsed.macroDefinitions = cloneConfigDependencyMacroExpansionDefinitions(event.parsed.macroDefinitions)
	}
	t.events = append(t.events, event)
	t.records += records
	t.bytes += bytes
}

// Detach all mutable scanner state used by include resolution and event replay.
// Immutable source/syntax observations can stay shared. A failed speculative
// lookup must not leak a diagnostic, generated binding, or partial queue edit.
func (s *configDependencyClosureScanner) headerReplayScanner() configDependencyClosureScanner {
	scratch := *s
	scratch.headerTrace = nil
	scratch.generatedText = maps.Clone(s.generatedText)
	if scratch.generatedText == nil {
		scratch.generatedText = map[string]configDependencyGeneratedText{}
	}
	scratch.resolvedGeneratedFiles = maps.Clone(s.resolvedGeneratedFiles)
	scratch.sourcePaths = maps.Clone(s.sourcePaths)
	scratch.objectPaths = maps.Clone(s.objectPaths)
	scratch.queued = maps.Clone(s.queued)
	scratch.queuedPhysical = maps.Clone(s.queuedPhysical)
	scratch.pending = slices.Clone(s.pending)
	scratch.conditionalFiles = maps.Clone(s.conditionalFiles)
	scratch.compilerGuardFiles = maps.Clone(s.compilerGuardFiles)
	scratch.conditionalParsed = cloneConfigDependencyParsedFiles(s.conditionalParsed)
	for identity, parsed := range scratch.conditionalParsed {
		parsed.macroDefinitions = cloneConfigDependencyMacroExpansionDefinitions(parsed.macroDefinitions)
		scratch.conditionalParsed[identity] = parsed
	}
	scratch.conditionalPending = maps.Clone(s.conditionalPending)
	scratch.conditionalRepeatGuards = maps.Clone(s.conditionalRepeatGuards)
	scratch.repeatedConditionalGuards = maps.Clone(s.repeatedConditionalGuards)
	scratch.macroExpansions = s.macroExpansions.clone()
	scratch.earlyMacroSummaries = maps.Clone(s.earlyMacroSummaries)
	return scratch
}

func (e configDependencyHeaderCacheEntry) replay(
	s *configDependencyClosureScanner,
	activePhysical map[string]*configDependencyConditionalActiveFile,
) (configDependencyClosureScanner, bool) {
	scratch := s.headerReplayScanner()
	for _, event := range e.events {
		switch event.kind {
		case configDependencyHeaderEnter:
			if activePhysical[event.file.identity()] != nil {
				return configDependencyClosureScanner{}, false
			}
			if event.file.configProjection || event.file.macroTable {
				scratch.queue(event.file)
			} else if !scratch.queueConditional(event.file) {
				return configDependencyClosureScanner{}, false
			}
		case configDependencyHeaderResolve:
			if !event.matchesResolution(&scratch) {
				return configDependencyClosureScanner{}, false
			}
		case configDependencyHeaderParsed:
			parsed := event.parsed
			parsed.macroDefinitions = cloneConfigDependencyMacroExpansionDefinitions(parsed.macroDefinitions)
			scratch.mergeConditionalParsed(event.file, parsed)
		case configDependencyHeaderGuard:
			scratch.recordConditionalRepeatGuard(event.file, event.guard)
		default:
			return configDependencyClosureScanner{}, false
		}
		if scratch.opaqueReason != "" {
			return configDependencyClosureScanner{}, false
		}
	}
	return scratch, true
}

func (e configDependencyHeaderEvent) matchesResolution(scanner *configDependencyClosureScanner) bool {
	if e.kind != configDependencyHeaderResolve {
		return false
	}
	actual, found := scanner.resolveIncludeFile(e.including, e.include)
	if !found || actual != e.file || scanner.opaqueReason != "" {
		return false
	}
	binding, valid := scanner.headerBinding(actual)
	return valid && binding == e.binding && scanner.opaqueReason == ""
}

// interpretDirectCompilerHeader is called only for definitely executed direct
// TU includes. Nested interpretation is recorded in the enclosing entry, not
// recursively cached. The source header itself was resolved live by the caller;
// every nested resolution is repeated on a hit, proving the same winning file
// and all earlier misses, including object-tree shadows and generated inputs.
func (s *configDependencyClosureScanner) interpretDirectCompilerHeader(
	file configDependencyScanFile,
	state *configDependencyMacroState,
	autoconf configDependencyResolvedAutoconfDefinitions,
	activePhysical map[string]*configDependencyConditionalActiveFile,
) bool {
	c := s.headerCache
	if c == nil || s.headerTrace != nil || !file.source || s.opaqueReason != "" ||
		!configDependencyMacroEffectStateReady(state) ||
		len(activePhysical) != 1 || activePhysical[file.identity()] != nil {
		return s.interpretConditionalCompilerFile(file, state, autoconf, activePhysical)
	}
	c.initialize()
	key := configDependencyHeaderCacheKey{
		file: file, profile: s.profile.Name, language: s.language,
		search:   configDependencyForcedHeaderSearchKey(s),
		autoconf: configDependencyForcedHeaderAutoconfKey(autoconf),
	}
	entries := c.entries[key]
	if reason, stopped := c.admissionLimit(len(entries)); stopped && len(entries) == 0 {
		// No entry can hit and no new entry can be admitted. In particular, do
		// not materialize the caller's sparse overlay just for this cache probe:
		// doing so would also make subsequent live writes update that tree eagerly.
		c.misses++
		c.reject(reason)
		return s.interpretConditionalCompilerFile(file, state, autoconf, activePhysical)
	}
	input, valid := state.materializedSnapshot()
	if !valid {
		return s.interpretConditionalCompilerFile(file, state, autoconf, activePhysical)
	}
	for _, entry := range entries {
		sameInput := entry.effect.input == input
		if !sameInput && !entry.specialization.matches(input) {
			c.requirementMismatches++
			continue
		}
		if scratch, exact := entry.replay(s, activePhysical); exact {
			applied := false
			if sameInput {
				applied = entry.effect.apply(state)
			} else {
				applied = entry.specialization.apply(state)
			}
			if !applied {
				s.setOpaque("cached compiler header macro-state commit is invalid")
				return false
			}
			*s = scratch
			c.hits++
			if sameInput {
				c.exactHits++
			} else {
				c.specializedHits++
			}
			return true
		}
		c.replayMismatches++
	}
	c.misses++
	if reason, stopped := c.admissionLimit(len(entries)); stopped {
		c.reject(reason)
		return s.interpretConditionalCompilerFile(file, state, autoconf, activePhysical)
	}
	trace := &configDependencyHeaderTrace{
		ancestors:      maps.Clone(activePhysical),
		maximumRecords: c.maximumRecords - c.records,
		maximumBytes:   c.maximumBytes - c.bytes,
	}
	child := state.branch()
	if child == nil || !child.beginForcedHeaderTrace() {
		c.reject(configDependencyHeaderRejectMacro)
		return s.interpretConditionalCompilerFile(file, state, autoconf, activePhysical)
	}
	c.captureAttempts++
	defer child.endForcedHeaderTrace()
	exact := func() bool {
		s.headerTrace = trace
		defer func() { s.headerTrace = nil }()
		return s.interpretConditionalCompilerFile(file, child, autoconf, activePhysical)
	}()
	if !exact {
		c.reject(configDependencyHeaderRejectInexact)
		if child != nil && child.tainted {
			state.tainted = true
		}
		return false
	}
	// Check retained support before constructing duplicate requirement/write
	// maps. Trace support itself is transient and follows the interpreted file;
	// neither an oversized trace nor an oversized specialization is retained.
	records, bytes := trace.records, trace.bytes
	macroTrace := child.forcedHeaderTrace
	records += macroTrace.reads.size() + child.forcedHeaderTouches.size() + child.snapshotChanges.exactSize()
	macroTrace.reads.forEach(func(name string) { bytes += len(name) })
	child.forcedHeaderTouches.forEach(func(name string) { bytes += len(name) })
	child.snapshotChanges.forEach(func(name string, _ configDependencyMacroSnapshotCell) { bytes += len(name) })
	bytes += len(key.profile) + len(key.language) + len(key.search) + len(file.logical) + len(file.physical)
	captured := false
	reason := configDependencyHeaderRejectMacro
	specialization := configDependencyMacroSpecialization{}
	switch {
	case trace.invalid:
		reason = trace.rejection
	case macroTrace.wholeNamespace:
		reason = configDependencyHeaderRejectWholeNamespace
	case macroTrace.invalid:
		reason = configDependencyHeaderRejectTrace
	case records > c.maximumRecords-c.records:
		reason = configDependencyHeaderRejectRecords
	case bytes > c.maximumBytes-c.bytes:
		reason = configDependencyHeaderRejectBytes
	default:
		if output, valid := child.materializedSnapshot(); valid {
			specialization, captured = captureConfigDependencyMacroSpecialization(child, input, output)
		}
	}
	child.endForcedHeaderTrace()
	effect := configDependencyMacroEffect{}
	if captured {
		effect, captured = captureConfigDependencyMacroEffect(child)
	}
	if !state.commitBranch(child) {
		c.reject(configDependencyHeaderRejectMacro)
		s.setOpaque("compiler header macro-state commit is invalid")
		return false
	}
	if !captured {
		c.reject(reason)
		return true
	}
	c.entries[key] = append(c.entries[key], configDependencyHeaderCacheEntry{effect: effect, specialization: specialization, events: trace.events})
	c.entryCount++
	c.records += records
	c.bytes += bytes
	c.stores++
	return true
}

func (s *configDependencyClosureScanner) mergeConditionalParsed(file configDependencyScanFile, parsed configDependencyParsedFile) {
	s.checkEarlyMacroSummary(file, parsed)
	s.headerTrace.record(configDependencyHeaderEvent{kind: configDependencyHeaderParsed, file: file, parsed: parsed})
	if s.conditionalParsed == nil {
		s.conditionalParsed = map[string]configDependencyParsedFile{}
	}
	identity := file.identity()
	s.conditionalParsed[identity] = mergeConfigDependencyConditionalParsed(s.conditionalParsed[identity], parsed)
}

func (s *configDependencyClosureScanner) recordConditionalRepeatGuard(file configDependencyScanFile, guard string) {
	s.headerTrace.record(configDependencyHeaderEvent{kind: configDependencyHeaderGuard, file: file, guard: guard})
	if s.conditionalRepeatGuards == nil {
		s.conditionalRepeatGuards = map[string]string{}
	}
	s.conditionalRepeatGuards[file.identity()] = guard
}
