package kconfig

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"maps"
	"slices"
	"strings"
)

// ConfigDependencyCompilerGuardObservation is a demand for a future compiler
// query, not a definedness answer or a successful source-closure receipt.
// Truncated invalidates its discovery frontier: baseline hints must be dropped
// together; an OptionalDefinedness truncation drops only optional demands.
// Compiler arguments retain the exact existing initial-state projection,
// including symbolic dependencies owned by the current Kbuild probe workload.
type ConfigDependencyCompilerGuardObservation struct {
	ConsumerNodeID              string
	Scope, Role, Language       string
	Arguments, TranslationUnits []string
	Environment                 map[string]string
	Names                       []string
	Calls                       []CompilerIntrinsicCall
	// OptionalDefinedness is exclusive to typed first-unknown expansion
	// demands. A rejected vector supplies no facts, not measured negatives.
	// Combined with Truncated it drops only optional demands, never the
	// preexisting static/intrinsic frontier.
	OptionalDefinedness bool
	// OptionalTokenHints are weaker inventories from entered files or bounded
	// literal-include candidates. Candidate discovery does not certify entry.
	// They must never share an attempt or admission tier with actual demands.
	OptionalTokenHints bool
	// LiteralIncludeHints marks the weaker, not-yet-entered subset of token
	// hints. Coordinators must preserve entered-file admission ahead of it.
	LiteralIncludeHints bool
	Truncated           bool
	Origin              ConfigDependencyCompilerGuardOrigin
}

// Source origins bind immutable input bytes. Optional token hints may describe
// a literal-include candidate which the source interpreter has not entered.
// Generated origins additionally require the validated observed-cut projection;
// a numeric macro summary or an unauthenticated exact-text hint cannot supply
// one. The enclosing round must also retain its complete execution-cut identity.
type ConfigDependencyCompilerGuardOrigin struct {
	Source                 bool
	LogicalPath, ContentID string
	OriginalProducerNodeID string
	Slot                   int
	Tree, OutputPath       string
}

// SetCompilerGuardObserver enables optional post-cut query discovery. This
// does not add requests to the ordinary Kbuild probe workload or change the
// macro namespace. The caller must execute and authenticate a separate frozen
// batch before applying any answers during a fresh analysis.
func (m *CompactMetadata) SetCompilerGuardObserver(observer func(ConfigDependencyCompilerGuardObservation) error) {
	m.compilerGuardObserver = observer
}

// SetCompilerGuardAnswers attaches a frozen, execution-measured supplemental
// namespace before analysis starts. Answers do not authenticate any source or
// generated bytes; the compiler scanner must still prove its current closure.
// A metadata/analysis snapshot must not change answers while it is in use.
func (m *CompactMetadata) SetCompilerGuardAnswers(answers *KbuildCompilerGuardAnswers) {
	m.compilerGuardAnswers = answers
}

func (s *configDependencyClosureScanner) rememberCompilerGuardFile(file configDependencyScanFile) {
	if !s.collectCompilerGuards || s.compilerGuardFilesTruncated || file.configProjection || file.macroTable {
		return
	}
	identity := file.identity()
	if identity == "" {
		return
	}
	if _, found := s.compilerGuardFiles[identity]; found {
		return
	}
	if len(s.compilerGuardFiles) >= 4096 {
		s.compilerGuardFilesTruncated = true
		s.compilerGuardFiles = nil
		return
	}
	if s.compilerGuardFiles == nil {
		s.compilerGuardFiles = map[string]configDependencyScanFile{}
	}
	s.compilerGuardFiles[identity] = file
}

func (s *configDependencyClosureScanner) emitCompilerGuardHints(
	probe configDependencyCompilerPredefineProbe,
	observe func(configDependencyCompilerPredefineProbe, configDependencyScanFile, configDependencyCompilerGuardHints, string),
) {
	// Cache replay restores the complete entered-file set even when it does
	// not interpret those nested headers again. Failed syntax is retained by
	// rememberCompilerGuardFile before queueConditional can reject it.
	for _, file := range s.conditionalFiles {
		s.rememberCompilerGuardFile(file)
	}
	if s.compilerGuardFilesTruncated {
		observe(probe, configDependencyScanFile{}, configDependencyCompilerGuardHints{truncated: true}, "")
		return
	}
	for _, identity := range slices.Sorted(maps.Keys(s.compilerGuardFiles)) {
		file := s.compilerGuardFiles[identity]
		key := s.conditionalSyntaxCacheKey(file)
		syntax := s.conditionalSyntax[key]
		if !syntax.compilerGuardHintsReady || !syntax.compilerTokenInventoryReady {
			// An earlier phase may have cached syntax without an observer.
			// Read only this already-entered immutable file, never its directory.
			contents, err := file.contents()
			if err != nil {
				continue // no bytes, no hints, and certainly no negative facts
			}
			if !syntax.compilerGuardHintsReady {
				syntax.compilerGuardHints = configDependencyCompilerGuardObservationHintsForContents(contents)
				syntax.compilerGuardHintsReady = true
			}
			if !syntax.compilerTokenInventoryReady {
				syntax.compilerTokenInventory = configDependencyOpenedHeaderTokenHintInventoryForProgram(len(contents), syntax.conditionalProgram)
				syntax.compilerTokenInventoryReady = true
			}
			syntax.compilerGuardContentID = fmt.Sprintf("%x", sha256.Sum256(contents))
			// A replay entry must already have syntax; do not fabricate a valid
			// conditional program if this optional hint encounters a missing one.
			if _, present := s.conditionalSyntax[key]; present {
				s.conditionalSyntax[key] = syntax
			}
		}
		hints := syntax.compilerGuardHints
		if probe.language != "c" && probe.language != "c++" {
			// The initial intrinsic protocol has no portable assembler dialect.
			hints.calls = nil
		}
		if len(hints.calls) != 0 {
			remaining := make([]CompilerIntrinsicCall, 0, len(hints.calls))
			for _, call := range hints.calls {
				// Only this operator's measured, nontextual initial binding
				// authorizes a query. Definedness hints remain available for a
				// later round when that binding is not ready yet.
				if !s.compilerIntrinsicInitialAvailable[call.Operator] {
					continue
				}
				cell, valid := s.compilerIntrinsicInitialSnapshot.lookup(call.Operand)
				if !valid || cell.definition != configDependencyMacroUndefined {
					// Static hints must not undefine known compiler macros merely
					// to ask an unused query (for example __LINE__ under -Werror).
					// Reached calls separately prove their current operand state.
					continue
				}
				answered := false
				if s.compilerIntrinsicAnswered != nil {
					var err error
					answered, err = s.compilerIntrinsicAnswered(call)
					if err != nil {
						// A contradictory snapshot never supplies a new demand or a
						// negative answer. Actual call consumption checks it separately.
						s.setOpaque("compiler intrinsic answers changed compiler context: " + err.Error())
						return
					}
				}
				if !answered {
					remaining = append(remaining, call)
				}
			}
			hints.calls = remaining
		}
		if !hints.truncated && len(s.compilerGuardInitialDefinitions) != 0 {
			// Both true and false are execution-measured initial facts. Source
			// writes, namespace absence and predefined dump omissions grant no
			// authority to suppress a supplemental compiler query.
			remaining := 0
			for _, name := range hints.names {
				if _, measured := s.compilerGuardInitialDefinitions[name]; !measured {
					remaining++
				}
			}
			if remaining != len(hints.names) {
				names := []string(nil)
				if remaining != 0 {
					names = make([]string, 0, remaining)
					for _, name := range hints.names {
						if _, measured := s.compilerGuardInitialDefinitions[name]; !measured {
							names = append(names, name)
						}
					}
				}
				hints.names = names // Never mutate the shared syntax-cache slice.
			}
		}
		if hints.truncated {
			observe(probe, file, hints, syntax.compilerGuardContentID)
			continue
		}
		// Query kinds are separate canonical manifest records, even when one
		// reached file supplies both kinds. Neither event grants source authority.
		if len(hints.names) != 0 {
			observe(probe, file, configDependencyCompilerGuardHints{names: hints.names}, syntax.compilerGuardContentID)
		}
		if len(hints.calls) != 0 {
			observe(probe, file, configDependencyCompilerGuardHints{calls: hints.calls}, syntax.compilerGuardContentID)
		}
	}
	s.emitCompilerOpenedHeaderTokenHints(probe, observe)
}

func (c *configDependencyAnalysisContext) recordCompilerGuardHints(
	plan *ActionPlan, node ActionPlanNode, role string,
	probe configDependencyCompilerPredefineProbe, file configDependencyScanFile,
	hints configDependencyCompilerGuardHints, contentID string,
) {
	if c.compilerGuardError != nil {
		return
	}
	if len(hints.names) != 0 && len(hints.calls) != 0 || hints.truncated && len(hints.names)+len(hints.calls) != 0 ||
		hints.optionalDefinedness && hints.optionalTokenHints ||
		hints.literalIncludeHints && !hints.optionalTokenHints ||
		(hints.optionalDefinedness || hints.optionalTokenHints) && (len(hints.calls) != 0 || !hints.truncated && len(hints.names) == 0) {
		c.compilerGuardError = fmt.Errorf("compiler guard observation mixes query kinds or retains truncated hints")
		return
	}
	observation := ConfigDependencyCompilerGuardObservation{
		ConsumerNodeID: strings.Clone(node.ID), Scope: actionPlanConfigDependencyScope(node),
		Role: role, Language: probe.language,
		Arguments: slices.Clone(probe.arguments), TranslationUnits: slices.Clone(probe.translationUnits),
		Environment: maps.Clone(probe.environment), Names: slices.Clone(hints.names), Calls: slices.Clone(hints.calls), Truncated: hints.truncated,
		OptionalDefinedness: hints.optionalDefinedness,
		OptionalTokenHints:  hints.optionalTokenHints,
		LiteralIncludeHints: hints.literalIncludeHints,
	}
	if file.logical == "" {
		if !hints.truncated || len(hints.names) != 0 || len(hints.calls) != 0 {
			c.compilerGuardError = fmt.Errorf("compiler guard hints lack an immutable file origin")
			return
		}
	} else if file.source {
		if file.physical == "" || file.exactIdentity != "" || file.configProjection || file.macroTable || contentID == "" {
			c.compilerGuardError = fmt.Errorf("compiler guard hints changed immutable source authority")
			return
		}
		observation.Origin = ConfigDependencyCompilerGuardOrigin{
			Source: true, LogicalPath: strings.Clone(file.logical), ContentID: contentID,
		}
	} else {
		// Only newConfigDependencyObservedHeaders can populate this map after
		// validating the completed cut, original producer, slot and bytes.
		if c.observedHeaders == nil {
			return
		}
		projection, found := c.observedHeaders.identities[file.exactIdentity]
		if !found {
			return
		}
		if file.physical != "" || file.configProjection || file.macroTable ||
			file.exactContents != projection.text.contents || contentID == "" {
			c.compilerGuardError = fmt.Errorf("compiler guard hints changed observed generated-header authority")
			return
		}
		observation.Origin = ConfigDependencyCompilerGuardOrigin{
			LogicalPath: strings.Clone(file.logical), ContentID: projection.contentID,
			OriginalProducerNodeID: projection.originalID, Slot: projection.text.slot,
			Tree: projection.output.Tree, OutputPath: projection.output.Path,
		}
	}
	if err := plan.metadata.compilerGuardObserver(observation); err != nil {
		c.compilerGuardError = fmt.Errorf("observe compiler guard demand: %w", err)
	}
}

// Supplement literal guard names with bounded direct intrinsic-call hints from
// the same complete reached-file bytes. These are only future query demands:
// source definitions, inactive text and malformed surrounding C grant no call
// authority. The ordered interpreter must independently prove the binding and
// terminal operand before consuming any measured answer.
func configDependencyCompilerGuardObservationHintsForContents(contents []byte) configDependencyCompilerGuardHints {
	hints := configDependencyCompilerGuardHintsForContents(contents)
	if hints.truncated {
		return hints
	}
	if !bytes.Contains(contents, []byte("__has_")) &&
		!bytes.Contains(contents, []byte("\\\n")) && !bytes.Contains(contents, []byte("\\\r\n")) {
		return hints
	}
	text, reason := configDependencyPreprocessorText(contents)
	if reason != "" {
		return hints
	}
	names := make(map[string]bool, len(hints.names))
	retainedBytes := 0
	for _, name := range hints.names {
		names[name] = true
		retainedBytes += len(name)
	}
	calls := map[CompilerIntrinsicCall]bool{}
	addName := func(name string) bool {
		// Ordinary absent names already have an exact initial negative fact.
		// Reserved operands, like __retain__, need an explicit compiler query.
		if !strings.HasPrefix(name, "_") || names[name] {
			return true
		}
		if len(names)+len(calls) >= configDependencyCompilerGuardHintsMaximumNames ||
			len(name) > configDependencyCompilerGuardHintsMaximumNameBytes-retainedBytes {
			return false
		}
		names[strings.Clone(name)] = true
		retainedBytes += len(name)
		return true
	}
	for line := range strings.SplitSeq(text, "\n") {
		// Per-line lexing preserves late hints beyond the lexer's span budget.
		// Unsupported lines omit hints, never supply negative evidence.
		tokens, err := configDependencyMacroCallLex(line, configDependencyMacroCallMode{})
		if err != nil {
			continue
		}
		for index := 0; index+3 < len(tokens); index++ {
			if !tokens[index].identifier || !isCompilerIntrinsicOperator(tokens[index].text) ||
				tokens[index+1].text != "(" || !tokens[index+2].identifier || tokens[index+3].text != ")" {
				continue
			}
			call := CompilerIntrinsicCall{Operator: tokens[index].text, Operand: tokens[index+2].text}
			if ValidateCompilerIntrinsicCall(call) != nil || calls[call] {
				continue
			}
			if !addName(call.Operator) || !addName(call.Operand) ||
				len(names)+len(calls) >= configDependencyCompilerGuardHintsMaximumNames ||
				len(call.Operator)+len(call.Operand) > configDependencyCompilerGuardHintsMaximumNameBytes-retainedBytes {
				return configDependencyCompilerGuardHints{truncated: true}
			}
			call.Operator, call.Operand = strings.Clone(call.Operator), strings.Clone(call.Operand)
			calls[call] = true
			retainedBytes += len(call.Operator) + len(call.Operand)
		}
	}
	hints.names = slices.Sorted(maps.Keys(names))
	for call := range calls {
		hints.calls = append(hints.calls, call)
	}
	slices.SortFunc(hints.calls, func(left, right CompilerIntrinsicCall) int {
		if order := strings.Compare(left.Operator, right.Operator); order != 0 {
			return order
		}
		return strings.Compare(left.Operand, right.Operand)
	})
	return hints
}

// Each callback observes the current immutable input file, not the location of
// a cached macro definition. The complete call proof separately records every
// replacement origin used to reach this occurrence. Missing answers can create
// future demands but always leave the current translation unit opaque.
func (s *configDependencyClosureScanner) configureCompilerIntrinsicQueries(
	plan *ActionPlan, node ActionPlanNode, role string,
	probe configDependencyCompilerPredefineProbe,
	observe func(configDependencyCompilerPredefineProbe, configDependencyScanFile, configDependencyCompilerGuardHints, string),
) {
	s.configureOptionalCompilerDefinedness(probe, observe)
	if probe.language != "c" && probe.language != "c++" {
		s.compilerIntrinsicAnswered = nil
		if s.callCoverage != nil {
			s.callCoverage.intrinsic = nil
		}
		return
	}
	lookup := func(call CompilerIntrinsicCall) (string, string, bool, error) {
		return configDependencySupplementalCompilerIntrinsic(
			plan, actionPlanConfigDependencyScope(node), role, probe.language,
			probe.arguments, probe.translationUnits, probe.environment, call,
		)
	}
	s.compilerIntrinsicAnswered = func(call CompilerIntrinsicCall) (bool, error) {
		_, _, ready, err := lookup(call)
		return ready, err
	}
	if s.callCoverage == nil {
		return
	}
	s.callCoverage.intrinsic = func(call CompilerIntrinsicCall) (string, string, string) {
		token, identity, ready, err := lookup(call)
		if err != nil {
			return "", "", "compiler intrinsic result cannot be replayed: " + err.Error()
		}
		if ready {
			return token, identity, ""
		}
		if observe != nil {
			file := s.compilerIntrinsicFile
			if file.logical == "" {
				return "", "", "compiler intrinsic demand has no reached file"
			}
			contents, err := file.contents()
			if err != nil {
				return "", "", "compiler intrinsic demand cannot read reached file: " + err.Error()
			}
			observe(probe, file, configDependencyCompilerGuardHints{calls: []CompilerIntrinsicCall{call}},
				fmt.Sprintf("%x", sha256.Sum256(contents)))
		}
		return "", "", "compiler intrinsic result is unavailable for " + call.Operator + "(" + call.Operand + ")"
	}
}

// Unlike the source hint inventory, this callback sees only the first unknown
// binding the structured macro engine actually tried to expand. Formal and
// unused arguments are consumed by that engine, not scanned as raw names. It
// never changes the current namespace, grants precision, or continues past the
// original failure. No compiler keyword or capability table is involved.
func (s *configDependencyClosureScanner) configureOptionalCompilerDefinedness(
	probe configDependencyCompilerPredefineProbe,
	observe func(configDependencyCompilerPredefineProbe, configDependencyScanFile, configDependencyCompilerGuardHints, string),
) {
	if s.callCoverage == nil {
		return
	}
	s.callCoverage.unknown = nil
	if !s.collectCompilerGuards || observe == nil || probe.language == "" || s.compilerIntrinsicInitialSnapshot == nil {
		return
	}
	s.callCoverage.unknown = func(name string) {
		if configDependencyAbsentMacroDefinition(name) != configDependencyMacroUnknown {
			return
		}
		initial, valid := s.compilerIntrinsicInitialSnapshot.lookup(name)
		if !valid || initial.definition != configDependencyMacroUnknown {
			return // Source mutation cannot revoke an existing initial answer.
		}
		if _, measured := s.compilerGuardInitialDefinitions[name]; measured {
			return
		}
		file := s.compilerIntrinsicFile
		if file.logical == "" {
			return
		}
		contents, err := file.contents()
		if err != nil {
			return // No immutable bytes, no demand and no facts.
		}
		contentID := fmt.Sprintf("%x", sha256.Sum256(contents))
		if len(contents) > configDependencyCompilerGuardHintsMaximumBytes || len(name) > configDependencyCompilerGuardHintsMaximumNameBytes {
			observe(probe, file, configDependencyCompilerGuardHints{truncated: true, optionalDefinedness: true}, contentID)
			return
		}
		observe(probe, file, configDependencyCompilerGuardHints{
			names: []string{name}, optionalDefinedness: true,
		}, contentID)
	}
}
