load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

package(default_visibility = ["//visibility:private"])

go_library(
    name = "ccprofile_lib",
    srcs = [
        "grep.go",
        "main.go",
        "nodes.go",
    ],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/ccprofile",
    deps = ["//internal/ccprofile"],
)

go_binary(
    name = "ccprofile",
    embed = [":ccprofile_lib"],
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "ccprofile_test",
    srcs = [
        "grep_test.go",
        "main_test.go",
        "nodes_test.go",
    ],
    embed = [":ccprofile_lib"],
    deps = ["//internal/ccprofile"],
)
