# gazelle:prefix github.com/hermeticbuild/linux.bzl
# gazelle:exclude aya_e2e
# gazelle:exclude e2e
# gazelle:exclude examples
# gazelle:resolve go github.com/bazelbuild/bazel-gazelle/rule @gazelle//rule

load("@buildifier_prebuilt//:rules.bzl", "buildifier", "buildifier_test")
load("@gazelle//:def.bzl", "gazelle", "gazelle_test")

package(default_visibility = ["//visibility:public"])

exports_files([
    "extensions.bzl",
    "linux.bzl",
    "source_repo.BUILD.bazel",
])

gazelle(
    name = "gazelle",
    extra_args = ["internal"],
)

gazelle_test(
    name = "gazelle_test",
    extra_args = ["internal"],
    tags = ["no-remote"],
    workspace = "//:MODULE.bazel",
)

buildifier(
    name = "buildifier",
    lint_mode = "fix",
    mode = "fix",
)

buildifier_test(
    name = "buildifier_test",
    lint_mode = "warn",
    lint_warnings = [
        "-module-docstring",
        "-function-docstring-args",
        "-function-docstring",
        "-function-docstring-header",
        "-function-docstring-return",
    ],
    no_sandbox = True,
    tags = ["no-remote"],
    workspace = "//:MODULE.bazel",
)
