load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "elf",
    srcs = [
        "lib/32.fsize.c",
        "lib/32.getehdr.c",
        "lib/32.getphdr.c",
        "lib/32.getshdr.c",
        "lib/32.newehdr.c",
        "lib/32.newphdr.c",
        "lib/32.xlatetof.c",
        "lib/64.xlatetof.c",
        "lib/assert.c",
        "lib/begin.c",
        "lib/checksum.c",
        "lib/cntl.c",
        "lib/cook.c",
        "lib/data.c",
        "lib/end.c",
        "lib/errmsg.c",
        "lib/errno.c",
        "lib/fill.c",
        "lib/flag.c",
        "lib/gelfehdr.c",
        "lib/gelfphdr.c",
        "lib/gelfshdr.c",
        "lib/gelf_shndx_compat.c",
        "lib/gelftrans.c",
        "lib/getarhdr.c",
        "lib/getaroff.c",
        "lib/getarsym.c",
        "lib/getbase.c",
        "lib/getdata.c",
        "lib/getident.c",
        "lib/getscn.c",
        "lib/hash.c",
        "lib/input.c",
        "lib/kind.c",
        "lib/ndxscn.c",
        "lib/newdata.c",
        "lib/newscn.c",
        "lib/next.c",
        "lib/nextscn.c",
        "lib/nlist.c",
        "lib/opt.delscn.c",
        "lib/rand.c",
        "lib/rawdata.c",
        "lib/rawfile.c",
        "lib/strptr.c",
        "lib/swap64.c",
        "lib/update.c",
        "lib/verdef_32_tof.c",
        "lib/verdef_32_tom.c",
        "lib/verdef_64_tof.c",
        "lib/verdef_64_tom.c",
        "lib/version.c",
        "lib/x.elfext.c",
        "lib/x.movscn.c",
        "lib/x.remscn.c",
    ],
    hdrs = glob([
        "include/**/*.h",
        "lib/*.h",
    ]),
    copts = [
        "-DHAVE_CONFIG_H=1",
        "-D__LIBELF_INTERNAL__=1",
        "-Wno-deprecated-non-prototype",
        "-Wno-implicit-function-declaration",
        "-Wno-incompatible-pointer-types",
        "-Wno-int-conversion",
        "-Wno-pointer-sign",
        "-Wno-unused-but-set-variable",
        "-Wno-unused-function",
        "-Wno-unused-variable",
    ],
    includes = [
        "include",
        "lib",
    ],
)
