load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "flagfilter_lib",
    srcs = ["main.go"],
    importpath = "linux.bzl/internal/cmd/flagfilter",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "flagfilter",
    embed = [":flagfilter_lib"],
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "flagfilter_test",
    srcs = ["main_test.go"],
    embed = [":flagfilter_lib"],
)
