module(
    name = "linux_bzl_aya_e2e",
    version = "0.0.0",
)

bazel_dep(name = "aya", version = "0.0.0")
bazel_dep(name = "linux.bzl", version = "0.1.0")
bazel_dep(name = "llvm", version = "0.8.14")
bazel_dep(name = "rules_rs", version = "0.0.98")

archive_override(
    module_name = "aya",
    integrity = "sha256-3+2/du1fBvpAB+65NtdWBeGE3By0d2/HfR3BstE7w7o=",
    patch_strip = 1,
    patches = [
        "//patches:aya_linux_bzl_api.patch",
        "//patches:aya_rust_kernel_module_e2e.patch",
    ],
    strip_prefix = "aya-05d5269f848e3565e964690fc7111817a2258033",
    urls = ["https://github.com/aya-rs/aya/archive/05d5269f848e3565e964690fc7111817a2258033.tar.gz"],
)

local_path_override(
    module_name = "linux.bzl",
    path = "..",
)

rules_rust = use_extension("@rules_rs//rs:rules_rust.bzl", "rules_rust")
use_repo(rules_rust, "rules_rust")

toolchains = use_extension(
    "@rules_rs//rs/toolchains:module_extension.bzl",
    "toolchains",
)
use_repo(toolchains, "default_rust_toolchains")

register_toolchains("@default_rust_toolchains//:all")
