load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "insnattr_lib",
    srcs = ["main.go"],
    importpath = "linux.bzl/internal/cmd/insnattr",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "insnattr",
    embed = [":insnattr_lib"],
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "insnattr_test",
    srcs = ["main_test.go"],
    embed = [":insnattr_lib"],
)
