load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "offsetsheader_lib",
    srcs = ["main.go"],
    importpath = "linux.bzl/internal/cmd/offsetsheader",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "offsetsheader",
    embed = [":offsetsheader_lib"],
    visibility = ["//:__subpackages__"],
)
