package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

var asciiRE = regexp.MustCompile(`^\s*\.ascii\s+"(.*)"`)

func main() {
	in := flag.String("in", "", "Assembly input containing Linux kbuild offset markers")
	out := flag.String("out", "", "Generated offsets header output")
	guard := flag.String("guard", "", "Header guard to emit")
	flag.Parse()

	if *in == "" || *out == "" || *guard == "" {
		fmt.Fprintln(os.Stderr, "-in, -out, and -guard are required")
		os.Exit(2)
	}
	if err := run(*in, *out, *guard); err != nil {
		fmt.Fprintf(os.Stderr, "offsetsheader: %v\n", err)
		os.Exit(1)
	}
}

func run(inPath, outPath, guard string) error {
	file, err := os.Open(inPath)
	if err != nil {
		return err
	}
	defer file.Close()

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	out, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer out.Close()

	fmt.Fprintf(out, "#ifndef %s\n", guard)
	fmt.Fprintf(out, "#define %s\n", guard)
	fmt.Fprintln(out, "/*")
	fmt.Fprintln(out, " * DO NOT MODIFY.")
	fmt.Fprintln(out, " *")
	fmt.Fprintln(out, " * This file was generated by Bazel")
	fmt.Fprintln(out, " */")
	fmt.Fprintln(out)

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		payload, ok, err := offsetPayload(scanner.Text())
		if err != nil {
			return err
		}
		if !ok {
			continue
		}
		if line := offsetHeaderLine(payload); line != "" {
			fmt.Fprintln(out, line)
		}
	}
	if err := scanner.Err(); err != nil {
		return err
	}

	fmt.Fprintln(out)
	fmt.Fprintln(out, "#endif")
	return nil
}

func offsetPayload(line string) (string, bool, error) {
	match := asciiRE.FindStringSubmatch(line)
	if match == nil {
		return "", false, nil
	}
	decoded, err := strconv.Unquote(`"` + match[1] + `"`)
	if err != nil {
		return "", false, err
	}
	if !strings.HasPrefix(decoded, "->") {
		return "", false, nil
	}
	return decoded[2:], true, nil
}

func offsetHeaderLine(payload string) string {
	if payload == "" {
		return ""
	}
	if strings.HasPrefix(payload, "#") {
		return "/* " + strings.TrimPrefix(payload, "#") + " */"
	}
	parts := strings.SplitN(payload, " ", 3)
	if len(parts) < 2 {
		return ""
	}
	sym := parts[0]
	value := strings.TrimLeft(parts[1], "$#")
	comment := ""
	if len(parts) == 3 {
		comment = parts[2]
	}
	return fmt.Sprintf("#define %s %s /* %s */", sym, value, comment)
}
