#ifndef CONFIG_FIXTURE
#error CONFIG_FIXTURE must be generated by linux_config
#endif

#ifndef CONFIG_FIXTURE_MODULE_MODULE
#error CONFIG_FIXTURE_MODULE=m must generate CONFIG_FIXTURE_MODULE_MODULE
#endif

#ifdef EXPECT_MODULE
#ifndef MODULE
#error linux_object mode=m must define MODULE
#endif
#endif

int linux_fixture_value(void) {
    return CONFIG_FIXTURE_VALUE;
}
