load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "mapdirectoryrecipe_lib",
    srcs = [
        "argument_chunks.go",
        "input_set_compact.go",
        "main.go",
    ],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/mapdirectoryrecipe",
    visibility = ["//visibility:private"],
    deps = [
        "//internal/kconfig",
        "//internal/toolaction",
        "//internal/toolsetpath",
    ],
)

go_binary(
    name = "mapdirectoryrecipe",
    embed = [":mapdirectoryrecipe_lib"],
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "mapdirectoryrecipe_test",
    srcs = [
        "argument_chunks_test.go",
        "input_set_compact_test.go",
        "main_test.go",
    ],
    embed = [":mapdirectoryrecipe_lib"],
    deps = [
        "//internal/kconfig",
        "//internal/toolaction",
    ],
)
