# gazelle:ignore

load("@bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
load("@rules_go//go:def.bzl", "go_binary", "go_test")

package(default_visibility = ["//:__subpackages__"])

go_binary(
    name = "init_binary",
    srcs = ["init.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/e2e/boot",
    pure = "on",
    visibility = ["//visibility:private"],
)

go_test(
    name = "init_test",
    srcs = [
        "init.go",
        "init_test.go",
    ],
    pure = "on",
)

platform_transition_filegroup(
    name = "init_x86_64",
    srcs = [":init_binary"],
    target_platform = "@rules_go//go/toolchain:linux_amd64",
)

platform_transition_filegroup(
    name = "init_aarch64",
    srcs = [":init_binary"],
    target_platform = "@rules_go//go/toolchain:linux_arm64",
)
