load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "kconfig_parse_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/kconfig_parse",
    visibility = ["//visibility:private"],
    deps = [
        "//internal/ccprofile",
        "//internal/kconfig",
        "//internal/rusttoolchain",
    ],
)

go_binary(
    name = "kconfig_parse",
    embed = [":kconfig_parse_lib"],
    pure = "on",
    visibility = ["//visibility:public"],
)

go_test(
    name = "kconfig_parse_test",
    srcs = ["main_test.go"],
    embed = [":kconfig_parse_lib"],
    deps = [
        "//internal/ccprofile",
        "//internal/kconfig",
        "//internal/rusttoolchain",
    ],
)
