load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "qemuboot_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/e2e/cmd/qemuboot",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "qemuboot",
    embed = [":qemuboot_lib"],
    pure = "on",
    visibility = ["//:__pkg__"],
)

go_test(
    name = "qemuboot_test",
    srcs = ["main_test.go"],
    embed = [":qemuboot_lib"],
)
