load("@bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
load("@tar.bzl//tar:tar.bzl", "tar")

package(default_visibility = ["//visibility:public"])

_PLATFORMS = [
    "darwin_amd64",
    "darwin_arm64",
    "linux_amd64",
    "linux_arm64",
    "windows_amd64",
    "windows_arm64",
]

_ARCHIVES = {
    "kconfig-darwin-amd64": "darwin_amd64",
    "kconfig-darwin-arm64": "darwin_arm64",
    "kconfig-linux-amd64": "linux_amd64",
    "kconfig-linux-arm64": "linux_arm64",
    "kconfig-windows-amd64": "windows_amd64",
    "kconfig-windows-arm64": "windows_arm64",
}

_ARCHIVE_TOOL_SUFFIXES = {
    "windows_amd64": ".exe",
    "windows_arm64": ".exe",
}

[
    platform_transition_filegroup(
        name = "kconfig_parse_for_" + platform,
        srcs = ["//internal/cmd/kconfig_parse"],
        target_platform = "@rules_go//go/toolchain:" + platform,
    )
    for platform in _PLATFORMS
]

[
    filegroup(
        name = "for_" + platform,
        srcs = [":kconfig_parse_for_" + platform],
    )
    for platform in _PLATFORMS
]

filegroup(
    name = "for_all_platforms",
    srcs = [
        ":for_darwin_amd64",
        ":for_darwin_arm64",
        ":for_linux_amd64",
        ":for_linux_arm64",
        ":for_windows_amd64",
        ":for_windows_arm64",
    ],
)

[
    tar(
        name = archive,
        srcs = [":kconfig_parse_for_" + platform],
        compress = "zstd",
        mtree = [
            "{} uid=0 gid=0 mode=0755 time=0 type=file content=$(location :kconfig_parse_for_{})".format(
                "kconfig_parse" + _ARCHIVE_TOOL_SUFFIXES.get(platform, ""),
                platform,
            ),
        ],
    )
    for archive, platform in _ARCHIVES.items()
]

filegroup(
    name = "kconfig_prebuilts",
    srcs = [
        ":kconfig-darwin-amd64",
        ":kconfig-darwin-arm64",
        ":kconfig-linux-amd64",
        ":kconfig-linux-arm64",
        ":kconfig-windows-amd64",
        ":kconfig-windows-arm64",
    ],
)
