load("@bazel_skylib//rules:build_test.bzl", "build_test")

package(default_visibility = ["//visibility:public"])

exports_files([
    "tiny.config",
    "tiny_arm64.config",
])

build_test(
    name = "linux_6_12_96_build_test",
    targets = [
        "@e2e_6_12_96_aarch64//:kernel",
        "@e2e_6_12_96_x86_64//:kernel",
    ],
)

alias(
    name = "kernel_image_aarch64",
    actual = "@e2e_aarch64//:image",
)

alias(
    name = "kernel_vmlinux_aarch64",
    actual = "@e2e_aarch64//:vmlinux",
)

alias(
    name = "kernel_image_x86_64",
    actual = "@e2e_x86_64//:image",
)

alias(
    name = "kernel_vmlinux_x86_64",
    actual = "@e2e_x86_64//:vmlinux",
)

build_test(
    name = "kernel_outputs_build_test",
    targets = [
        "@e2e_aarch64//:config",
        "@e2e_aarch64//:kernel",
        "@e2e_aarch64//:kernel_release",
        "@e2e_aarch64//:system_map",
        "@e2e_x86_64//:config",
        "@e2e_x86_64//:kernel",
        "@e2e_x86_64//:kernel_release",
        "@e2e_x86_64//:system_map",
        ":kernel_image_aarch64",
        ":kernel_image_x86_64",
        ":kernel_vmlinux_aarch64",
        ":kernel_vmlinux_x86_64",
    ],
)
