module(
    name = "linux_bzl_e2e",
    version = "0.0.0",
)

bazel_dep(name = "bazel_lib", version = "3.2.2")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "linux.bzl", version = "0.0.1")
bazel_dep(name = "llvm", version = "0.8.14", repo_name = "hermetic_llvm")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_go", version = "0.62.0")
bazel_dep(name = "rules_qemu", version = "0.3.0")
bazel_dep(name = "rules_rs", version = "0.0.98")

register_toolchains(
    "@hermetic_llvm//toolchain:all",
)

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.nogo(nogo = "@rules_go//:tools_nogo")

rust_toolchains = use_extension("@rules_rs//rs/toolchains:module_extension.bzl", "toolchains")
rust_toolchains.toolchain(
    version = "1.97.0",
)
use_repo(rust_toolchains, "default_rust_toolchains")

register_toolchains("@default_rust_toolchains//:all")

local_path_override(
    module_name = "linux.bzl",
    path = "..",
)

qemu = use_extension("@rules_qemu//qemu/extension:qemu.bzl", "qemu")
qemu.system_toolchain(
    system_target = "x86_64-softmmu",
    target_settings = ["//:qemu_system_x86_64"],
)
qemu.system_toolchain(
    system_target = "aarch64-softmmu",
    target_settings = ["//:qemu_system_aarch64"],
)
use_repo(
    qemu,
    "qemu_system_toolchains",
    "qemu_user_toolchains",
)

register_toolchains("@qemu_system_toolchains//:all")

linux_source_repository = use_repo_rule(
    "@linux.bzl//:linux.bzl",
    "linux_source_repository",
)

linux_source_repository(
    name = "e2e_linux_6_12_96",
    version = "6.12.96",
)

linux_source_repository(
    name = "e2e_linux_6_18_39",
    version = "6.18.39",
)

linux_images = use_extension("@linux.bzl//:extensions.bzl", "linux_images")
linux_images.image(
    name = "e2e_6_12_96_x86_64",
    config = "//:tiny.config",
    platform = "@hermetic_llvm//platforms:linux_x86_64",
    source = "@e2e_linux_6_12_96//:Kconfig",
)
linux_images.image(
    name = "e2e_6_12_96_aarch64",
    config = "//:tiny_arm64.config",
    platform = "@hermetic_llvm//platforms:linux_arm64",
    source = "@e2e_linux_6_12_96//:Kconfig",
)
linux_images.image(
    name = "e2e_rust_6_12_96_x86_64",
    config = "//:rust.config",
    platform = "@hermetic_llvm//platforms:linux_x86_64",
    source = "@e2e_linux_6_12_96//:Kconfig",
)
linux_images.image(
    name = "e2e_rust_6_12_96_aarch64",
    config = "//:rust_arm64.config",
    platform = "@hermetic_llvm//platforms:linux_arm64",
    source = "@e2e_linux_6_12_96//:Kconfig",
)
linux_images.image(
    name = "e2e_x86_64",
    config = "//:tiny.config",
    platform = "@hermetic_llvm//platforms:linux_x86_64",
    source = "@e2e_linux_6_18_39//:Kconfig",
)
linux_images.image(
    name = "e2e_rust_x86_64",
    config = "//:rust.config",
    platform = "@hermetic_llvm//platforms:linux_x86_64",
    source = "@e2e_linux_6_18_39//:Kconfig",
)
linux_images.image(
    name = "e2e_rust_aarch64",
    config = "//:rust_arm64.config",
    platform = "@hermetic_llvm//platforms:linux_arm64",
    source = "@e2e_linux_6_18_39//:Kconfig",
)
linux_images.image(
    name = "e2e_aarch64",
    config = "//:tiny_arm64.config",
    platform = "@hermetic_llvm//platforms:linux_arm64",
    source = "@e2e_linux_6_18_39//:Kconfig",
)
use_repo(
    linux_images,
    "e2e_6_12_96_aarch64",
    "e2e_6_12_96_x86_64",
    "e2e_aarch64",
    "e2e_rust_6_12_96_aarch64",
    "e2e_rust_6_12_96_x86_64",
    "e2e_rust_aarch64",
    "e2e_rust_x86_64",
    "e2e_x86_64",
)
