module(
    name = "linux_bzl_e2e",
    version = "0.0.0",
)

bazel_dep(name = "linux.bzl", version = "0.0.0")
bazel_dep(name = "llvm", version = "0.7.1")
bazel_dep(name = "platforms", version = "1.0.0")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "libelf",
    build_file = "//:libelf.BUILD.bazel",
    integrity = "sha256-WRqbTsgcHyBCqXqmBWTgy3nQQcUvqnQWrLOLyVvSx20=",
    patch_cmds = [
        """cat > lib/config.h <<'EOF'
#include <stdint.h>
#define STDC_HEADERS 1
#define ENABLE_EXTENDED_FORMAT 1
#define ENABLE_SANITY_CHECKS 1
#define HAVE_AR_H 1
#define HAVE_ELF_H 1
#define HAVE_FCNTL_H 1
#define HAVE_FTRUNCATE 1
#define HAVE_GETPAGESIZE 1
#define HAVE_LINK_H 1
#define HAVE_MEMCMP 1
#define HAVE_MEMCPY 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMSET 1
#define HAVE_MMAP 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define __LIBELF64 1
#define __LIBELF64_LINUX 1
#define __LIBELF_GNU_SYMBOL_VERSIONS 1
#define __LIBELF_HEADER_ELF_H <elf.h>
#define __LIBELF_SYMBOL_VERSIONS 1
#define __libelf_i16_t int16_t
#define __libelf_i32_t int32_t
#define __libelf_i64_t int64_t
#define __libelf_u16_t uint16_t
#define __libelf_u32_t uint32_t
#define __libelf_u64_t uint64_t
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_SHORT 2
EOF""",
        "awk 'BEGIN { emit = 0 } /Ok, now get the correct instance/ { emit = 1 } emit { print }' lib/sys_elf.h.in > lib/sys_elf.h",
        "mkdir -p include/libelf && cp lib/libelf.h lib/gelf.h lib/nlist.h lib/sys_elf.h include/ && cp lib/libelf.h lib/gelf.h lib/nlist.h lib/sys_elf.h lib/elf_repl.h include/libelf/",
    ],
    strip_prefix = "libelf-0.8.13",
    urls = [
        "https://www.mirrorservice.org/sites/ftp.netbsd.org/pub/pkgsrc/distfiles/libelf-0.8.13.tar.gz",
        "https://fossies.org/linux/misc/old/libelf-0.8.13.tar.gz",
    ],
)

register_toolchains(
    "@llvm//toolchain:all",
    dev_dependency = True,
)

local_path_override(
    module_name = "linux.bzl",
    path = "..",
)

linux_kernel = use_extension("@linux.bzl//:linux.bzl", "linux_kernel")
linux_kernel.archive(
    name = "linux_6_18_2",
    integrity = "sha256-VYxrurdJSSs0+Zgn/oB7ADmnRGk8IdOn4Ds6SO2quWo=",
    strip_prefix = "linux-6.18.2",
    urls = ["https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.18.2.tar.xz"],
)
linux_kernel.kconfig(
    name = "tiny_kconfig",
    config = "//:tiny.config",
)
linux_kernel.compact(
    name = "tiny_compact",
    config = "//:tiny.config",
    config_name = "x86_64",
    kernel_name = "kernel",
    source_repo = "linux_6_18_2",
)
use_repo(
    linux_kernel,
    "linux_6_18_2",
    "tiny_compact",
    "tiny_kconfig",
)
