load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "runandwrite_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/runandwrite",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "runandwrite",
    embed = [":runandwrite_lib"],
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "runandwrite_test",
    srcs = ["main_test.go"],
    embed = [":runandwrite_lib"],
)
