module(
    name = "linux_image_tagging_dependency",
    version = "1.0.0",
)

bazel_dep(name = "linux.bzl", version = "0.1.0")
bazel_dep(name = "llvm", version = "0.8.14")

linux_images = use_extension("@linux.bzl//:extensions.bzl", "linux_images")
linux_images.image(
    name = "dependency_kernel",
    config = "//:base.config",
    platform = "@llvm//platforms:linux_x86_64",
    source = "//:Kconfig",
)
