load("@rules_go//go:def.bzl", "go_test")

package(default_visibility = ["//visibility:public"])

go_test(
    name = "armv7_test",
    srcs = ["artifact_test.go"],
    data = [
        "//:armv7.config",
        "//:hello_c_module_armv7",
        "@e2e_armv7//:config",
        "@e2e_armv7//:image",
        "@e2e_armv7//:vmlinux",
    ],
    env = {
        "ARCH": "armv7",
        "ELF_CLASS": "32",
        "ELF_MACHINE": "arm",
        "IMAGE_FORMAT": "arm-zimage",
        "INFERRED_CONFIG": "CONFIG_ARM",
        "INPUT_CONFIG": "$(rlocationpath //:armv7.config)",
        "KERNEL_ELF_TYPE": "exec",
        "KERNEL_CONFIG": "$(rlocationpath @e2e_armv7//:config)",
        "KERNEL_IMAGE": "$(rlocationpath @e2e_armv7//:image)",
        "KERNEL_MODULE": "$(rlocationpath //:hello_c_module_armv7)",
        "KERNEL_VMLINUX": "$(rlocationpath @e2e_armv7//:vmlinux)",
        "REQUIRED_CONFIGS": "CONFIG_SYSVIPC,CONFIG_HIGH_RES_TIMERS,CONFIG_BPF_SYSCALL,CONFIG_ARCH_ASPEED,CONFIG_MACH_ASPEED_G6,CONFIG_ARCH_NPCM,CONFIG_MODULES",
    },
    pure = "on",
    rundir = ".",
    deps = ["@rules_go//go/runfiles"],
)
