load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "orchash_lib",
    srcs = ["main.go"],
    importpath = "linux.bzl/internal/cmd/orchash",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "orchash",
    embed = [":orchash_lib"],
    visibility = ["//:__subpackages__"],
)
