load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "kconfig_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/kconfig",
    visibility = ["//visibility:private"],
    deps = [
        "//internal/kconfig/buildgen",
        "@com_github_bazelbuild_buildtools//build",
    ],
)

go_binary(
    name = "kconfig",
    embed = [":kconfig_lib"],
    pure = "on",
    visibility = ["//visibility:public"],
)

go_test(
    name = "kconfig_test",
    srcs = ["main_test.go"],
    embed = [":kconfig_lib"],
    deps = ["@com_github_bazelbuild_buildtools//build"],
)

filegroup(
    name = "kconfig_prebuilts",
    srcs = ["//internal/cmd/kconfig/prebuilts:kconfig_prebuilts"],
)
