package main

import (
	"reflect"
	"strings"
	"testing"

	build "github.com/bazelbuild/buildtools/build"
)

func TestParseKconfig(t *testing.T) {
	got, err := parseKconfig(strings.NewReader(`
CONFIG_BOOL=y
CONFIG_MODULE=m
# CONFIG_DISABLED is not set
CONFIG_FALSE=n
CONFIG_STRING="value"
CONFIG_INT=12
CONFIG_HEX=0x1f
CONFIG_lower-case.symbol=m

# unrelated comment
`))
	if err != nil {
		t.Fatalf("parseKconfig() failed: %v", err)
	}

	want := map[string]string{
		"CONFIG_BOOL":              "y",
		"CONFIG_FALSE":             "n",
		"CONFIG_HEX":               "0x1f",
		"CONFIG_INT":               "12",
		"CONFIG_MODULE":            "m",
		"CONFIG_STRING":            `"value"`,
		"CONFIG_lower-case.symbol": "m",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("parseKconfig() = %#v, want %#v", got, want)
	}
}

func TestParseKconfigRejectsDuplicates(t *testing.T) {
	_, err := parseKconfig(strings.NewReader("CONFIG_DUP=y\nCONFIG_DUP=m\n"))
	if err == nil {
		t.Fatal("parseKconfig() succeeded on duplicate key")
	}
}

func TestUpdateBuildfileRewritesNamedRule(t *testing.T) {
	input := []byte(`load("@linux.bzl//internal:kconfig.bzl", "kconfig_import")

kconfig_import(
    name = "other",
    config_flags = {
        "CONFIG_KEEP": "y",
    },
)

kconfig_import(
    name = "sample",
    config_flags = {
        "CONFIG_OLD": "y",
    },
)
`)
	got, err := updateBuildfile(input, "BUILD.bazel", "sample", map[string]string{
		"CONFIG_ALPHA": "y",
		"CONFIG_MOD":   "m",
	})
	if err != nil {
		t.Fatalf("updateBuildfile() failed: %v", err)
	}

	want := `load("@linux.bzl//internal:kconfig.bzl", "kconfig_import")

kconfig_import(
    name = "other",
    config_flags = {
        "CONFIG_KEEP": "y",
    },
)

kconfig_import(
    name = "sample",
    config_flags = {
        "CONFIG_ALPHA": "y",
        "CONFIG_MOD": "m",
    },
)
`
	if string(got) != want {
		t.Fatalf("updateBuildfile() =\n%s\nwant:\n%s", got, want)
	}
}

func TestUpdateBuildfileAddsMissingConfigFlags(t *testing.T) {
	input := []byte(`kconfig_import(
    name = "sample",
)
`)
	got, err := updateBuildfile(input, "BUILD.bazel", "sample", map[string]string{"CONFIG_A": "y"})
	if err != nil {
		t.Fatalf("updateBuildfile() failed: %v", err)
	}

	want := `kconfig_import(
    name = "sample",
    config_flags = {
        "CONFIG_A": "y",
    },
)
`
	if string(got) != want {
		t.Fatalf("updateBuildfile() =\n%s\nwant:\n%s", got, want)
	}
}

func TestRemoveConfigFlags(t *testing.T) {
	input := []byte(`load("@linux.bzl//internal:kconfig.bzl", "kconfig_import")

kconfig_import(
    name = "sample",
    config = "sample.config",
    config_flags = {
        "CONFIG_A": "y",
    },
)
`)
	got, err := removeConfigFlags(input, "BUILD.bazel", "sample")
	if err != nil {
		t.Fatalf("removeConfigFlags() failed: %v", err)
	}

	want := `load("@linux.bzl//internal:kconfig.bzl", "kconfig_import")

kconfig_import(
    name = "sample",
    config = "sample.config",
)
`
	if string(got) != want {
		t.Fatalf("removeConfigFlags() =\n%s\nwant:\n%s", got, want)
	}
}

func TestUpdateBuildfileErrorsOnDuplicateRule(t *testing.T) {
	input := []byte(`kconfig_import(name = "sample")
kconfig_import(name = "sample")
`)
	_, err := updateBuildfile(input, "BUILD.bazel", "sample", map[string]string{})
	if err == nil {
		t.Fatal("updateBuildfile() succeeded on duplicate rule")
	}
}

func TestFormatConfigFlagsIsDeterministic(t *testing.T) {
	got := build.FormatString(configFlagsExpr(map[string]string{
		"CONFIG_A": "y",
		"CONFIG_Z": "m",
	}))
	want := `{
    "CONFIG_A": "y",
    "CONFIG_Z": "m",
}`
	if got != want {
		t.Fatalf("configFlagsExpr() =\n%s\nwant:\n%s", got, want)
	}
}

func TestConfigBuildfile(t *testing.T) {
	got, err := configBuildfile("BUILD.bazel", "kconfig", "//pkg:source.config", map[string]string{
		"CONFIG_A":   "y",
		"CONFIG_MOD": "m",
	}, []string{"//pkg:__pkg__"})
	if err != nil {
		t.Fatalf("configBuildfile() failed: %v", err)
	}

	want := `# Generated by kconfig. Do not edit.

load("@linux.bzl//internal:kconfig.bzl", "kconfig_file")

exports_files(["BUILD.bazel"])

kconfig_file(
    name = "kconfig",
    config = "//pkg:source.config",
    config_flags = {
        "CONFIG_A": "y",
        "CONFIG_MOD": "m",
    },
    visibility = ["//pkg:__pkg__"],
)
`
	if string(got) != want {
		t.Fatalf("configBuildfile() =\n%s\nwant:\n%s", got, want)
	}
}
