load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "arm64headers_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/arm64headers",
    visibility = ["//visibility:private"],
    deps = ["//internal/kconfig"],
)

go_binary(
    name = "arm64headers",
    embed = [":arm64headers_lib"],
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "arm64headers_test",
    srcs = ["main_test.go"],
    embed = [":arm64headers_lib"],
)
