load("@linux.bzl", "initramfs")

package(default_visibility = ["//visibility:public"])

initramfs(
    name = "example_initramfs",
    character_devices = {
        "/dev/console": "5:1",
        "/dev/null": "1:3",
    },
    directories = ["/proc"],
    files = {
        "/etc/motd": "README.md",
    },
)

alias(
    name = "x86_64_kernel",
    actual = "@example_x86_64//:kernel",
)

alias(
    name = "x86_64_debug_kernel",
    actual = "@example_x86_64//variants/debug:kernel",
)

alias(
    name = "x86_64_lz4_kernel",
    actual = "@example_x86_64//variants/lz4:kernel",
)

alias(
    name = "aarch64_kernel",
    actual = "@example_aarch64//:kernel",
)
