load("@linux.bzl", "initramfs")

package(default_visibility = ["//visibility:public"])

initramfs(
    name = "example_initramfs",
    character_devices = {
        "/dev/console": "5:1",
        "/dev/null": "1:3",
    },
    directories = ["/proc"],
    files = {
        "/etc/motd": "README.md",
    },
)

alias(
    name = "x86_64_kernel",
    actual = "@example_x86_64//:kernel",
)

alias(
    name = "x86_64_debug_kernel",
    actual = "@example_x86_64//variants/debug:kernel",
)

alias(
    name = "x86_64_btf_vmlinux",
    actual = "@example_x86_64//variants/btf:vmlinux",
)

alias(
    name = "x86_64_lz4_kernel",
    actual = "@example_x86_64//variants/lz4:kernel",
)

genrule(
    name = "x86_64_shared_graph_metadata",
    srcs = ["@example_x86_64//graph:metadata.json"],
    outs = ["x86_64_shared_graph_metadata.json"],
    cmd = "cp $(location @example_x86_64//graph:metadata.json) $@",
    tags = [
        "local",
        "manual",
    ],
)

alias(
    name = "aarch64_kernel",
    actual = "@example_aarch64//:kernel",
)
