load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "initramfsdata_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/initramfsdata",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "initramfsdata",
    embed = [":initramfsdata_lib"],
    visibility = ["//:__subpackages__"],
)
