load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "crctables_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/crctables",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "crctables",
    embed = [":crctables_lib"],
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "crctables_test",
    srcs = ["main_test.go"],
    embed = [":crctables_lib"],
)
