# gazelle:ignore

load("@rules_go//go:def.bzl", "go_binary", "go_test")

go_binary(
    name = "rustcversionrun",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/rustcversionrun",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "rustcversionrun_test",
    srcs = [
        "main.go",
        "main_test.go",
    ],
)
