load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@bazel_skylib//rules:select_file.bzl", "select_file")

package(default_visibility = ["//visibility:public"])

exports_files(["sonic.config"])

filegroup(
    name = "ngbde_main_source",
    srcs = ["@sonic_linux_6_18_39//:drivers/net/ethernet/broadcom/sdklt/linux/bde/ngbde_main.c"],
)

select_file(
    name = "linux_ngbde_ko",
    srcs = "@sonic_kernel//:modules",
    subpath = "linux_ngbde.ko",
)

build_test(
    name = "sonic_linux_ngbde_module_test",
    targets = [
        ":linux_ngbde_ko",
        ":ngbde_main_source",
        "@sonic_arm64_kernel//:modules",
    ],
)
