load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load("@rules_go//go:def.bzl", "go_test")

package(default_visibility = ["//visibility:public"])

exports_files([
    "gcc_toolchain_remote_execution.patch",
    "libbpf_old_uapi_compat.patch",
    "llvm_kbuild_actions.patch",
    "sai_bcm_kconfig.patch",
    "sonic.config",
])

string_flag(
    name = "compiler",
    build_setting_default = "clang",
    values = [
        "clang",
        "gcc",
    ],
)

config_setting(
    name = "gcc_selected",
    flag_values = {":compiler": "gcc"},
)

toolchain(
    name = "gcc_cc_toolchain_aarch64",
    exec_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    target_compatible_with = [
        "@platforms//cpu:aarch64",
        "@platforms//os:linux",
    ],
    target_settings = [":gcc_selected"],
    toolchain = "@sonic_gcc_aarch64//:_cc_toolchain",
    toolchain_type = "@rules_cc//cc:toolchain_type",
)

toolchain(
    name = "gcc_cc_toolchain_x86_64",
    exec_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    target_settings = [":gcc_selected"],
    toolchain = "@sonic_gcc_x86_64//:_cc_toolchain",
    toolchain_type = "@rules_cc//cc:toolchain_type",
)

go_test(
    name = "sonic_linux_ngbde_module_test",
    srcs = ["module_test.go"],
    data = [
        "@sonic_kernel//:config",
        "@sonic_kernel//:linux_ngbde",
    ],
    env = {
        "LINUX_NGBDE_MODULE": "$(rlocationpath @sonic_kernel//:linux_ngbde)",
        "SONIC_X86_CONFIG": "$(rlocationpath @sonic_kernel//:config)",
    },
    pure = "on",
    rundir = ".",
    deps = ["@rules_go//go/runfiles"],
)

go_test(
    name = "sonic_arm64_module_exclusion_test",
    srcs = ["arm64_module_test.go"],
    data = [
        "@sonic_arm64_kernel//:config",
        "@sonic_arm64_kernel//:modules",
    ],
    env = {
        "SONIC_ARM64_CONFIG": "$(rlocationpath @sonic_arm64_kernel//:config)",
        "SONIC_ARM64_MODULES": "$(rlocationpath @sonic_arm64_kernel//:modules)",
    },
    pure = "on",
    rundir = ".",
    deps = ["@rules_go//go/runfiles"],
)
