#ifndef LINUX_BZL_EXTERNAL_FROM_KBUILD_EXTMOD_H
#define LINUX_BZL_EXTERNAL_FROM_KBUILD_EXTMOD_H

#define LINUX_BZL_EXTERNAL_FROM_KBUILD_EXTMOD_OK 1

#endif /* LINUX_BZL_EXTERNAL_FROM_KBUILD_EXTMOD_H */
