load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "btfmutate_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/btfmutate",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "btfmutate",
    embed = [":btfmutate_lib"],
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "btfmutate_test",
    srcs = ["main_test.go"],
    embed = [":btfmutate_lib"],
)
