load("@linux.bzl", "initramfs")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

initramfs(
    name = "archive",
    character_devices = {
        "/dev/null": "1:3",
    },
    directories = [
        "/empty",
        "/empty/dir",
    ],
    executables = {
        "/bin/tool": "tool.txt",
        "/init": "tool.txt",
        "/usr/bin/tool": "tool.txt",
    },
    files = {
        "/etc/config": "config.txt",
    },
    symlinks = {
        "/bin/config": "/etc/config",
    },
)

initramfs(
    name = "archive_reordered",
    character_devices = {
        "/dev/null": "1:3",
    },
    directories = [
        "/empty/dir",
        "/empty",
    ],
    executables = {
        "/usr/bin/tool": "tool.txt",
        "/init": "tool.txt",
        "/bin/tool": "tool.txt",
    },
    files = {
        "/etc/config": "config.txt",
    },
    symlinks = {
        "/bin/config": "/etc/config",
    },
)

cc_test(
    name = "initramfs_test",
    srcs = ["initramfs_test.c"],
    args = [
        "$(location :archive)",
        "$(location :archive_reordered)",
    ],
    data = [
        ":archive",
        ":archive_reordered",
    ],
)
