load(":integration_test.bzl", "integration_test")

integration_test(
    name = "linux_image_extension_integration_test",
    size = "large",
    timeout = "moderate",
    src = "linux_image_extension_integration_test.sh",
    data = [
        "//:extensions.bzl",
        "//internal:linux_image_extension_integration_files",
    ] + glob(["fixture/**"]),
    tags = [
        "local",
        "no-remote",
    ],
)
