obj-$(CONFIG_MAP_DIRECTORY_CC_SUPPORTED) += supported.o
obj-$(CONFIG_MAP_DIRECTORY_CC_UNSUPPORTED) += unsupported.o
obj-$(CONFIG_MAP_DIRECTORY_CLANG_SELECTED) += clang_selected.o
obj-$(CONFIG_MAP_DIRECTORY_GCC_SELECTED) += gcc_selected.o
obj-m += composite.o
composite-y += composite_first.o composite_second.o

CFLAGS_supported.o += -fno-omit-frame-pointer -DMAP_DIRECTORY_RECIPE_REPLAYED=1
CFLAGS_clang_selected.o += -DMAP_DIRECTORY_CLANG_RECIPE_REPLAYED=1
CFLAGS_gcc_selected.o += -DMAP_DIRECTORY_GCC_RECIPE_REPLAYED=1
CFLAGS_composite_first.o += -DMAP_DIRECTORY_COMPOSITE_FIRST=1
CFLAGS_composite_second.o += -DMAP_DIRECTORY_COMPOSITE_SECOND=1
