load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "conmakehash_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/conmakehash",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "conmakehash",
    embed = [":conmakehash_lib"],
    visibility = ["//:__subpackages__"],
)
