package main

import (
	"bufio"
	"flag"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

type inputList []string

func (l *inputList) String() string {
	return strings.Join(*l, ",")
}

func (l *inputList) Set(value string) error {
	*l = append(*l, value)
	return nil
}

var defineRE = regexp.MustCompile(`^\s*#\s*define\s+(__HYPERVISOR_[a-z][a-z_0-9]*)\s+(\S+)`)

func main() {
	var inputs inputList
	out := flag.String("out", "", "Generated xen-hypercalls.h output")
	flag.Var(&inputs, "in", "Xen interface header input. May be repeated.")
	flag.Parse()

	if *out == "" || len(inputs) == 0 {
		fmt.Fprintln(os.Stderr, "-out and at least one -in are required")
		os.Exit(2)
	}
	if err := run(inputs, *out); err != nil {
		fmt.Fprintf(os.Stderr, "xenhypercalls: %v\n", err)
		os.Exit(1)
	}
}

func run(inputs []string, out string) error {
	valueToDefine := map[string]string{}
	for _, input := range inputs {
		if err := scanHeader(input, valueToDefine); err != nil {
			return err
		}
	}

	lines := map[string]bool{}
	for _, define := range valueToDefine {
		if _, alias := valueToDefine[define]; alias {
			continue
		}
		name := strings.TrimPrefix(define, "__HYPERVISOR_")
		lines["HYPERCALL("+name+")"] = true
	}

	sorted := slices.Sorted(maps.Keys(lines))

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	file, err := os.Create(out)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintln(file, "/* auto-generated by Bazel xenhypercalls. */")
	for _, line := range sorted {
		fmt.Fprintln(file, line)
	}
	return nil
}

func scanHeader(path string, valueToDefine map[string]string) error {
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		matches := defineRE.FindStringSubmatch(scanner.Text())
		if matches == nil {
			continue
		}
		valueToDefine[matches[2]] = matches[1]
	}
	if err := scanner.Err(); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	return nil
}
