package main

import (
	_ "embed"
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/hermeticbuild/linux.bzl/internal/kconfig"
)

//go:embed main.go
var kernelflagsSource string

const testKernelVersion = "6.18.2"

func TestKernelFlagsConfigSymbolsCoverSource(t *testing.T) {
	known := map[string]bool{}
	for _, symbol := range kconfig.KernelFlagsConfigSymbols() {
		known[symbol] = true
	}
	// Batch payload materialization reproduces kernel.release, whose footprint
	// is already tracked with the generated-header inputs rather than global
	// compiler flags.
	known["CONFIG_LOCALVERSION"] = true
	for _, token := range regexp.MustCompile(`CONFIG_[A-Z0-9_]+`).FindAllString(kernelflagsSource, -1) {
		if !known[token] {
			t.Errorf("kernelflags reads %s but it is absent from kconfig.KernelFlagsConfigSymbols()", token)
		}
	}
}

func TestMaterializeConfigPayloads(t *testing.T) {
	const id = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	const payload = "CONFIG_ALPHA=y\n# CONFIG_DISABLED is not set\nCONFIG_LOCALVERSION=\"-test\"\nCONFIG_MODULE=m\nCONFIG_NUMBER=7\nCONFIG_STRING=\"value\"\n"
	tempDir := t.TempDir()
	manifestPath := filepath.Join(tempDir, "manifest.json")
	encodedPayload, err := json.Marshal(payload)
	if err != nil {
		t.Fatal(err)
	}
	manifest := `{"arch":"x86","payloads":{"` + id + `":` + string(encodedPayload) + `},"version":"6.18.39"}` + "\n"
	if err := os.WriteFile(manifestPath, []byte(manifest), 0o644); err != nil {
		t.Fatal(err)
	}
	outDir := filepath.Join(tempDir, "payloads")
	if err := materializeConfigPayloads(manifestPath, outDir); err != nil {
		t.Fatal(err)
	}

	config := map[string]string{
		"CONFIG_ALPHA":        "y",
		"CONFIG_DISABLED":     "n",
		"CONFIG_LOCALVERSION": "\"-test\"",
		"CONFIG_MODULE":       "m",
		"CONFIG_NUMBER":       "7",
		"CONFIG_STRING":       "\"value\"",
	}
	root := filepath.Join(outDir, id)
	autoConf := filepath.Join(root, "include", "config", "auto.conf")
	expected := map[string]string{
		filepath.Join(root, ".config"): configText(config),
		autoConf:                       configText(config),
		filepath.Join(root, "include", "config", "auto.conf.cmd"):  "'cmd_" + filepath.ToSlash(autoConf) + " := bazel linux_config'\n",
		filepath.Join(root, "include", "config", "kernel.release"): "6.18.39-test\n",
		filepath.Join(root, "include", "generated", "autoconf.h"): strings.Join([]string{
			"/* Generated by Bazel linux_config. */",
			"#ifndef __GENERATED_AUTOCONF_H__",
			"#define __GENERATED_AUTOCONF_H__",
			"#define CONFIG_ALPHA 1",
			"#define CONFIG_LOCALVERSION \"-test\"",
			"#define CONFIG_MODULE_MODULE 1",
			"#define CONFIG_NUMBER 7",
			"#define CONFIG_STRING \"value\"",
			"#endif",
			"",
		}, "\n"),
		filepath.Join(root, "include", "generated", "integer-wrap.h"): "",
		filepath.Join(root, "include", "generated", "rustc_cfg"): strings.Join([]string{
			"--cfg=CONFIG_ALPHA",
			"--cfg=CONFIG_ALPHA=\"y\"",
			"--cfg=CONFIG_LOCALVERSION=\"-test\"",
			"--cfg=CONFIG_MODULE",
			"--cfg=CONFIG_MODULE=\"m\"",
			"--cfg=CONFIG_NUMBER=\"7\"",
			"--cfg=CONFIG_STRING=\"value\"",
			"",
		}, "\n"),
		filepath.Join(root, "include", "generated", "bazel_kbuild_aflags.rsp"): responseFile(linuxAFlags(config, "x86", "6.18.39")),
		filepath.Join(root, "include", "generated", "bazel_kbuild_cflags.rsp"): responseFile(linuxCFlags(config, "x86", "6.18.39")),
	}
	for path, want := range expected {
		got, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("read %s: %v", path, err)
			continue
		}
		if string(got) != want {
			t.Errorf("%s content mismatch:\nwant:\n%s\ngot:\n%s", path, want, got)
		}
	}
}

func TestMaterializeConfigPayloadsRejectsInvalidID(t *testing.T) {
	tempDir := t.TempDir()
	manifestPath := filepath.Join(tempDir, "manifest.json")
	if err := os.WriteFile(
		manifestPath,
		[]byte(`{"arch":"x86","payloads":{"../escape":"CONFIG_TEST=y\n"},"version":"6.18.39"}`+"\n"),
		0o644,
	); err != nil {
		t.Fatal(err)
	}
	err := materializeConfigPayloads(manifestPath, filepath.Join(tempDir, "payloads"))
	if err == nil || !strings.Contains(err.Error(), "invalid payload ID") {
		t.Fatalf("materializeConfigPayloads() error = %v, want invalid payload ID", err)
	}
}

func TestMaterializeConfigPayloadFiles(t *testing.T) {
	const id = "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789"
	tempDir := t.TempDir()
	payloadPath := filepath.Join(tempDir, "payload.config")
	if err := os.WriteFile(
		payloadPath,
		[]byte("CONFIG_ALPHA=y\nCONFIG_LOCALVERSION=\"-files\"\n"),
		0o644,
	); err != nil {
		t.Fatal(err)
	}
	outDir := filepath.Join(tempDir, "payloads")
	if err := materializeConfigPayloadFiles(
		[]string{id + "=" + payloadPath},
		outDir,
		"arm64",
		"6.18.39",
	); err != nil {
		t.Fatal(err)
	}
	root := filepath.Join(outDir, id)
	for path, want := range map[string]string{
		filepath.Join(root, ".config"):                             "CONFIG_ALPHA=y\nCONFIG_LOCALVERSION=\"-files\"\n",
		filepath.Join(root, "include", "config", "kernel.release"): "6.18.39-files\n",
	} {
		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		if string(got) != want {
			t.Fatalf("%s = %q, want %q", path, got, want)
		}
	}
}

func TestMaterializeConfigPayloadFilesRejectsDuplicateID(t *testing.T) {
	const id = "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789"
	err := materializeConfigPayloadFiles(
		[]string{id + "=/first", id + "=/second"},
		t.TempDir(),
		"x86",
		"6.18.39",
	)
	if err == nil || !strings.Contains(err.Error(), "repeated payload ID") {
		t.Fatalf("materializeConfigPayloadFiles() error = %v, want repeated payload ID", err)
	}
}

func TestLinuxAFlagsX86IncludeFtraceUsingDefines(t *testing.T) {
	config := map[string]string{
		"CONFIG_FUNCTION_TRACER":      "y",
		"CONFIG_FTRACE_MCOUNT_USE_CC": "y",
		"CONFIG_HAVE_FENTRY":          "y",
		"CONFIG_X86_64":               "y",
	}
	flags := linuxAFlags(config, "x86", testKernelVersion)
	if !contains(flags, "-DCC_USING_FENTRY") {
		t.Fatalf("linuxAFlags() missing -DCC_USING_FENTRY: %v", flags)
	}
	if contains(flags, "-mfentry") {
		t.Fatalf("linuxAFlags() leaked C-only -mfentry into assembly flags: %v", flags)
	}
}

func TestLinuxCFlagsX86IncludeFtraceCompilerAndUsingFlags(t *testing.T) {
	config := map[string]string{
		"CONFIG_FUNCTION_TRACER":      "y",
		"CONFIG_FTRACE_MCOUNT_USE_CC": "y",
		"CONFIG_HAVE_FENTRY":          "y",
		"CONFIG_X86_64":               "y",
	}
	flags := linuxCFlags(config, "x86", testKernelVersion)
	for _, want := range []string{"-pg", "-mrecord-mcount", "-mfentry", "-DCC_USING_FENTRY"} {
		if !contains(flags, want) {
			t.Fatalf("linuxCFlags() missing %s: %v", want, flags)
		}
	}
}

func TestLinuxCFlagsX86ExcludeGCCOnlyAlignmentFlag(t *testing.T) {
	flags := linuxCFlags(map[string]string{"CONFIG_X86_64": "y"}, "x86", testKernelVersion)
	if contains(flags, "-falign-jumps=1") {
		t.Fatalf("linuxCFlags() contains GCC-only -falign-jumps=1: %v", flags)
	}
}

func TestLinuxCFlagsX86UPUseGlobalStackProtectorGuard(t *testing.T) {
	for _, test := range []struct {
		config  map[string]string
		version string
	}{
		{
			config: map[string]string{
				"CONFIG_STACKPROTECTOR": "y",
				"CONFIG_X86_64":         "y",
			},
			version: "6.15",
		},
		{
			config: map[string]string{
				"CONFIG_STACKPROTECTOR": "y",
			},
			version: "6.12.96",
		},
	} {
		flags := linuxCFlags(test.config, "x86", test.version)
		if !contains(flags, "-mstack-protector-guard=global") {
			t.Fatalf("linuxCFlags() missing global stack-protector guard: %v", flags)
		}
		for _, unwanted := range []string{
			"-mstack-protector-guard-reg=fs",
			"-mstack-protector-guard-reg=gs",
			"-mstack-protector-guard-symbol=__ref_stack_chk_guard",
		} {
			if contains(flags, unwanted) {
				t.Fatalf("linuxCFlags() unexpectedly contains %s: %v", unwanted, flags)
			}
		}
	}
}

func TestLinuxCFlagsX8664Before615UsesFixedStackProtectorCanary(t *testing.T) {
	for _, smp := range []bool{false, true} {
		config := map[string]string{
			"CONFIG_STACKPROTECTOR":        "y",
			"CONFIG_STACKPROTECTOR_STRONG": "y",
			"CONFIG_X86_64":                "y",
		}
		if smp {
			config["CONFIG_SMP"] = "y"
		}
		for _, version := range []string{"6.12.96", "6.14.11", "v6.14"} {
			flags := linuxCFlags(config, "x86", version)
			if !contains(flags, "-fstack-protector-strong") {
				t.Fatalf("linuxCFlags(%q, SMP=%t) disabled stack protection: %v", version, smp, flags)
			}
			for _, flag := range flags {
				if strings.HasPrefix(flag, "-mstack-protector-guard") {
					t.Fatalf("linuxCFlags(%q, SMP=%t) overrides the fixed %%gs:40 canary with %s: %v", version, smp, flag, flags)
				}
			}
		}
	}
}

func TestLinuxCFlagsX86SMPUsePerCPUStackProtectorGuard(t *testing.T) {
	for _, test := range []struct {
		config  map[string]string
		reg     string
		version string
	}{
		{
			config: map[string]string{
				"CONFIG_SMP":            "y",
				"CONFIG_STACKPROTECTOR": "y",
				"CONFIG_X86_64":         "y",
			},
			reg:     "gs",
			version: "6.15-rc1",
		},
		{
			config: map[string]string{
				"CONFIG_SMP":            "y",
				"CONFIG_STACKPROTECTOR": "y",
			},
			reg:     "fs",
			version: "6.12.96",
		},
	} {
		flags := linuxCFlags(test.config, "x86", test.version)
		for _, want := range []string{
			"-mstack-protector-guard-reg=" + test.reg,
			"-mstack-protector-guard-symbol=__ref_stack_chk_guard",
		} {
			if !contains(flags, want) {
				t.Fatalf("linuxCFlags() missing %s: %v", want, flags)
			}
		}
		if contains(flags, "-mstack-protector-guard=global") {
			t.Fatalf("linuxCFlags() unexpectedly contains global guard: %v", flags)
		}
	}
}

func TestKernelVersionAtLeast(t *testing.T) {
	for _, test := range []struct {
		version string
		want    bool
	}{
		{version: "6.12.96", want: false},
		{version: "v6.14", want: false},
		{version: "6.15-rc1", want: true},
		{version: "6.15.0", want: true},
		{version: "7.0", want: true},
		{version: "", want: false},
		{version: "test", want: false},
	} {
		if got := kernelVersionAtLeast(test.version, 6, 15); got != test.want {
			t.Errorf("kernelVersionAtLeast(%q, 6, 15) = %t, want %t", test.version, got, test.want)
		}
	}
}

func TestLinuxCFlagsIncludeClangThinLTO(t *testing.T) {
	config := map[string]string{
		"CONFIG_CC_IS_CLANG":    "y",
		"CONFIG_LTO_CLANG_THIN": "y",
	}
	flags := linuxCFlags(config, "arm64", testKernelVersion)
	for _, want := range []string{"-fno-lto", "-flto=thin", "-fsplit-lto-unit", "-fvisibility=hidden"} {
		if !contains(flags, want) {
			t.Fatalf("linuxCFlags() missing %s: %v", want, flags)
		}
	}
}

func TestLinuxCFlagsIncludeClangFullLTO(t *testing.T) {
	config := map[string]string{
		"CONFIG_CC_IS_CLANG":    "y",
		"CONFIG_LTO_CLANG_FULL": "y",
	}
	flags := linuxCFlags(config, "arm64", testKernelVersion)
	for _, want := range []string{"-fno-lto", "-flto", "-fvisibility=hidden"} {
		if !contains(flags, want) {
			t.Fatalf("linuxCFlags() missing %s: %v", want, flags)
		}
	}
}

func TestLinuxCFlagsUseSectionSplittingForDeadCodeElimination(t *testing.T) {
	config := map[string]string{
		"CONFIG_LD_DEAD_CODE_DATA_ELIMINATION": "y",
	}
	flags := linuxCFlags(config, "arm64", testKernelVersion)
	for _, want := range []string{"-ffunction-sections", "-fdata-sections"} {
		if !contains(flags, want) {
			t.Fatalf("linuxCFlags() missing %s: %v", want, flags)
		}
	}
	for _, unwanted := range []string{"-fno-function-sections", "-fno-data-sections"} {
		if contains(flags, unwanted) {
			t.Fatalf("linuxCFlags() unexpectedly contains %s: %v", unwanted, flags)
		}
	}
}

func TestLinuxCFlagsUseO2ForPerformanceOptimization(t *testing.T) {
	config := map[string]string{
		"CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE": "y",
	}
	flags := linuxCFlags(config, "arm64", testKernelVersion)
	if !contains(flags, "-O2") {
		t.Fatalf("linuxCFlags() missing -O2: %v", flags)
	}
	if contains(flags, "-Os") {
		t.Fatalf("linuxCFlags() unexpectedly contains -Os: %v", flags)
	}
}

func TestLinuxCFlagsUseOsForSizeOptimization(t *testing.T) {
	config := map[string]string{
		"CONFIG_CC_OPTIMIZE_FOR_SIZE": "y",
	}
	flags := linuxCFlags(config, "arm64", testKernelVersion)
	if !contains(flags, "-Os") {
		t.Fatalf("linuxCFlags() missing -Os: %v", flags)
	}
	if contains(flags, "-O2") {
		t.Fatalf("linuxCFlags() unexpectedly contains -O2: %v", flags)
	}
}

func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
