load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "realmoderelocs_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/realmoderelocs",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "realmoderelocs",
    embed = [":realmoderelocs_lib"],
    visibility = ["//:__subpackages__"],
)
