"""Macros for source-tree-specific x86 Linux host tools."""

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load(":common_host_tools.bzl", "linux_common_host_tools")
load(":linux_objects.bzl", "linux_x86_generated_headers")
load(":source_utils.bzl", "package_label", "source_label", "source_labels")

_X86_OBJTOOL_TEXTUAL_HDRS = [
    "tools/arch/x86/include/asm/amd/ibs.h",
    "tools/arch/x86/include/asm/asm.h",
    "tools/arch/x86/include/asm/atomic.h",
    "tools/arch/x86/include/asm/barrier.h",
    "tools/arch/x86/include/asm/cmpxchg.h",
    "tools/arch/x86/include/asm/cpufeatures.h",
    "tools/arch/x86/include/asm/emulate_prefix.h",
    "tools/arch/x86/include/asm/inat.h",
    "tools/arch/x86/include/asm/inat_types.h",
    "tools/arch/x86/include/asm/insn.h",
    "tools/arch/x86/include/asm/io.h",
    "tools/arch/x86/include/asm/msr-index.h",
    "tools/arch/x86/include/asm/nops.h",
    "tools/arch/x86/include/asm/orc_types.h",
    "tools/arch/x86/include/asm/pvclock-abi.h",
    "tools/arch/x86/include/asm/pvclock.h",
    "tools/arch/x86/include/asm/rmwcc.h",
    "tools/arch/x86/include/asm/special_insns.h",
    "tools/arch/x86/include/uapi/asm/bitsperlong.h",
    "tools/arch/x86/include/uapi/asm/errno.h",
    "tools/arch/x86/include/uapi/asm/kvm.h",
    "tools/arch/x86/include/uapi/asm/mman.h",
    "tools/arch/x86/include/uapi/asm/perf_regs.h",
    "tools/arch/x86/include/uapi/asm/svm.h",
    "tools/arch/x86/include/uapi/asm/unistd.h",
    "tools/arch/x86/include/uapi/asm/unistd_32.h",
    "tools/arch/x86/include/uapi/asm/unistd_64.h",
    "tools/arch/x86/include/uapi/asm/vmx.h",
    "tools/arch/x86/lib/inat.c",
    "tools/arch/x86/lib/insn.c",
    "tools/include/asm-generic/atomic-gcc.h",
    "tools/include/asm-generic/barrier.h",
    "tools/include/asm-generic/bitops.h",
    "tools/include/asm-generic/bitops/__ffs.h",
    "tools/include/asm-generic/bitops/__ffz.h",
    "tools/include/asm-generic/bitops/__fls.h",
    "tools/include/asm-generic/bitops/arch_hweight.h",
    "tools/include/asm-generic/bitops/atomic.h",
    "tools/include/asm-generic/bitops/const_hweight.h",
    "tools/include/asm-generic/bitops/fls.h",
    "tools/include/asm-generic/bitops/fls64.h",
    "tools/include/asm-generic/bitops/hweight.h",
    "tools/include/asm-generic/bitops/non-atomic.h",
    "tools/include/asm-generic/bitsperlong.h",
    "tools/include/asm-generic/hugetlb_encode.h",
    "tools/include/asm-generic/io.h",
    "tools/include/asm/alternative.h",
    "tools/include/asm/atomic.h",
    "tools/include/asm/barrier.h",
    "tools/include/asm/bug.h",
    "tools/include/asm/export.h",
    "tools/include/asm/io.h",
    "tools/include/asm/rwonce.h",
    "tools/include/asm/sections.h",
    "tools/include/asm/timex.h",
    "tools/include/generated/asm-offsets.h",
    "tools/include/generated/asm/cpucap-defs.h",
    "tools/include/generated/asm/sysreg-defs.h",
    "tools/include/linux/align.h",
    "tools/include/linux/args.h",
    "tools/include/linux/atomic.h",
    "tools/include/linux/bitfield.h",
    "tools/include/linux/bitmap.h",
    "tools/include/linux/bitops.h",
    "tools/include/linux/bits.h",
    "tools/include/linux/bug.h",
    "tools/include/linux/build_bug.h",
    "tools/include/linux/cache.h",
    "tools/include/linux/cfi_types.h",
    "tools/include/linux/compiler-gcc.h",
    "tools/include/linux/compiler.h",
    "tools/include/linux/compiler_types.h",
    "tools/include/linux/const.h",
    "tools/include/linux/container_of.h",
    "tools/include/linux/ctype.h",
    "tools/include/linux/err.h",
    "tools/include/linux/export.h",
    "tools/include/linux/filter.h",
    "tools/include/linux/find.h",
    "tools/include/linux/hash.h",
    "tools/include/linux/hashtable.h",
    "tools/include/linux/interval_tree_generic.h",
    "tools/include/linux/jhash.h",
    "tools/include/linux/kallsyms.h",
    "tools/include/linux/kasan-tags.h",
    "tools/include/linux/kconfig.h",
    "tools/include/linux/kern_levels.h",
    "tools/include/linux/kernel.h",
    "tools/include/linux/list.h",
    "tools/include/linux/list_sort.h",
    "tools/include/linux/log2.h",
    "tools/include/linux/math.h",
    "tools/include/linux/math64.h",
    "tools/include/linux/objtool_types.h",
    "tools/include/linux/overflow.h",
    "tools/include/linux/panic.h",
    "tools/include/linux/poison.h",
    "tools/include/linux/rbtree.h",
    "tools/include/linux/rbtree_augmented.h",
    "tools/include/linux/refcount.h",
    "tools/include/linux/ring_buffer.h",
    "tools/include/linux/sizes.h",
    "tools/include/linux/static_call_types.h",
    "tools/include/linux/string.h",
    "tools/include/linux/stringify.h",
    "tools/include/linux/types.h",
    "tools/include/linux/unaligned.h",
    "tools/include/linux/unaligned/packed_struct.h",
    "tools/include/linux/zalloc.h",
    "tools/include/tools/be_byteshift.h",
    "tools/include/tools/endian.h",
    "tools/include/tools/le_byteshift.h",
    "tools/include/uapi/asm-generic/bitsperlong.h",
    "tools/include/uapi/asm-generic/errno-base.h",
    "tools/include/uapi/asm-generic/errno.h",
    "tools/include/uapi/asm-generic/mman-common.h",
    "tools/include/uapi/asm-generic/mman.h",
    "tools/include/uapi/asm-generic/unistd.h",
    "tools/include/uapi/asm/bitsperlong.h",
    "tools/include/uapi/asm/errno.h",
    "tools/include/uapi/linux/bits.h",
    "tools/include/uapi/linux/bpf_common.h",
    "tools/include/uapi/linux/const.h",
    "tools/include/uapi/linux/elf.h",
    "tools/include/uapi/linux/mman.h",
    "tools/include/uapi/linux/stddef.h",
    "tools/include/uapi/linux/types.h",
    "tools/include/vdso/bits.h",
    "tools/include/vdso/const.h",
    "tools/include/vdso/unaligned.h",
    "tools/lib/subcmd/exec-cmd.h",
    "tools/lib/subcmd/help.h",
    "tools/lib/subcmd/pager.h",
    "tools/lib/subcmd/parse-options.h",
    "tools/lib/subcmd/run-command.h",
    "tools/lib/subcmd/sigchain.h",
    "tools/lib/subcmd/subcmd-config.h",
    "tools/lib/subcmd/subcmd-util.h",
    "tools/objtool/arch/x86/include/arch/cfi_regs.h",
    "tools/objtool/arch/x86/include/arch/elf.h",
    "tools/objtool/arch/x86/include/arch/special.h",
    "tools/objtool/include/objtool/arch.h",
    "tools/objtool/include/objtool/builtin.h",
    "tools/objtool/include/objtool/cfi.h",
    "tools/objtool/include/objtool/check.h",
    "tools/objtool/include/objtool/elf.h",
    "tools/objtool/include/objtool/endianness.h",
    "tools/objtool/include/objtool/objtool.h",
    "tools/objtool/include/objtool/orc.h",
    "tools/objtool/include/objtool/special.h",
    "tools/objtool/include/objtool/warn.h",
    "tools/objtool/noreturns.h",
]

_X86_OBJTOOL_SRCS = [
    "tools/lib/ctype.c",
    "tools/lib/rbtree.c",
    "tools/lib/str_error_r.c",
    "tools/lib/string.c",
    "tools/lib/subcmd/exec-cmd.c",
    "tools/lib/subcmd/help.c",
    "tools/lib/subcmd/pager.c",
    "tools/lib/subcmd/parse-options.c",
    "tools/lib/subcmd/run-command.c",
    "tools/lib/subcmd/sigchain.c",
    "tools/lib/subcmd/subcmd-config.c",
    "tools/objtool/arch/x86/decode.c",
    "tools/objtool/arch/x86/orc.c",
    "tools/objtool/arch/x86/special.c",
    "tools/objtool/builtin-check.c",
    "tools/objtool/check.c",
    "tools/objtool/elf.c",
    "tools/objtool/objtool.c",
    "tools/objtool/orc_dump.c",
    "tools/objtool/orc_gen.c",
    "tools/objtool/special.c",
    "tools/objtool/weak.c",
]

def linux_x86_host_tools(
        name,
        config,
        source_repo,
        target_prefix = None,
        source_root = None,
        source_tree = None,
        env = None,
        visibility = None):
    """Defines the source-tree-specific host tools required by x86 native builds."""
    if env == None:
        env = {
            "ARCH": "x86",
            "SRCARCH": "x86",
        }
    common = linux_common_host_tools(
        name = name,
        env = env,
        source_repo = source_repo,
        source_root = source_root,
        source_tree = source_tree,
        target_prefix = target_prefix,
        visibility = visibility,
    )
    if target_prefix == None:
        target_prefix = name

    generated_headers = target_prefix + "_x86_generated_headers"
    objtool_inat_tables = target_prefix + "_x86_objtool_inat_tables"
    objtool_inputs = target_prefix + "_x86_objtool_inputs"
    objtool = target_prefix + "_x86_objtool"
    relocs_sources = target_prefix + "_x86_relocs_sources"
    relocs_tool = target_prefix + "_x86_relocs_tool"

    linux_x86_generated_headers(
        name = generated_headers,
        asm_offsets_c = source_label(source_repo, "arch/x86/kernel/asm-offsets.c"),
        bounds_c = source_label(source_repo, "kernel/bounds.c"),
        config = config,
        cpufeatures_h = source_label(source_repo, "arch/x86/include/asm/cpufeatures.h"),
        kvm_asm_offsets_c = source_label(source_repo, "arch/x86/kvm/kvm-asm-offsets.c"),
        orc_types_h = source_label(source_repo, "arch/x86/include/asm/orc_types.h"),
        rq_offsets_c = source_label(source_repo, "kernel/sched/rq-offsets.c"),
        source_root = common.source_root,
        source_tree = common.source_tree,
        syscall_32_tbl = source_label(source_repo, "x86_syscall_32_tbl"),
        syscall_64_tbl = source_label(source_repo, "x86_syscall_64_tbl"),
        visibility = visibility,
        xen_interface_headers = source_labels(source_repo, [
            "include/xen/interface/xen-mca.h",
            "include/xen/interface/xen.h",
            "include/xen/interface/xenpmu.h",
        ]),
    )

    genrule_inat_out = target_prefix + "_x86_objtool_inat/arch/x86/lib/inat-tables.c"
    native.genrule(
        name = objtool_inat_tables,
        srcs = [source_label(source_repo, "arch/x86/lib/x86-opcode-map.txt")],
        outs = [genrule_inat_out],
        cmd = "$(location @linux.bzl//tools:insnattr) -in $(location %s) -out $@" % source_label(source_repo, "arch/x86/lib/x86-opcode-map.txt"),
        tools = ["@linux.bzl//tools:insnattr"],
        visibility = visibility,
    )

    cc_library(
        name = objtool_inputs,
        includes = [genrule_inat_out[:-len("/inat-tables.c")]],
        textual_hdrs = [":" + objtool_inat_tables] + source_labels(source_repo, _X86_OBJTOOL_TEXTUAL_HDRS),
        visibility = visibility,
    )

    cc_binary(
        name = objtool,
        srcs = source_labels(source_repo, _X86_OBJTOOL_SRCS),
        copts = [
            "-D_GNU_SOURCE",
            "-Dbswap_16=__bswap_16",
            "-Dbswap_32=__bswap_32",
            "-Dbswap_64=__bswap_64",
            "-Wno-missing-field-initializers",
            "-Wno-nested-externs",
            "-Wno-packed",
            "-Wno-switch-default",
            "-Wno-switch-enum",
            "-Wno-unused-parameter",
        ],
        linkstatic = True,
        visibility = visibility,
        deps = [
            ":" + objtool_inputs,
            Label("@libelf//:elf"),
            source_label(source_repo, "tools_headers_cc"),
        ],
    )

    native.genrule(
        name = relocs_sources,
        srcs = [source_label(source_repo, "arch/x86/tools/relocs.c")],
        outs = [
            target_prefix + "_x86_relocs_32.c",
            target_prefix + "_x86_relocs_64.c",
        ],
        cmd = "\n".join([
            "cat > $(location %s_x86_relocs_32.c) <<'EOF'" % target_prefix,
            "#include \"relocs.h\"",
            "#define ELF_BITS 32",
            "#define ELF_MACHINE EM_386",
            "#define ELF_MACHINE_NAME \"i386\"",
            "#define SHT_REL_TYPE SHT_REL",
            "#define Elf_Rel Elf32_Rel",
            "#define ELF_CLASS ELFCLASS32",
            "#define ELF_R_SYM(val) ELF32_R_SYM(val)",
            "#define ELF_R_TYPE(val) ELF32_R_TYPE(val)",
            "#define ELF_ST_TYPE(o) ELF32_ST_TYPE(o)",
            "#define ELF_ST_BIND(o) ELF32_ST_BIND(o)",
            "#define ELF_ST_VISIBILITY(o) ELF32_ST_VISIBILITY(o)",
            "#ifndef R_386_NONE",
            "#define R_386_NONE 0",
            "#endif",
            "#ifndef R_386_32",
            "#define R_386_32 1",
            "#endif",
            "#ifndef R_386_PC32",
            "#define R_386_PC32 2",
            "#endif",
            "#ifndef R_386_GOT32",
            "#define R_386_GOT32 3",
            "#endif",
            "#ifndef R_386_PLT32",
            "#define R_386_PLT32 4",
            "#endif",
            "#ifndef R_386_COPY",
            "#define R_386_COPY 5",
            "#endif",
            "#ifndef R_386_GLOB_DAT",
            "#define R_386_GLOB_DAT 6",
            "#endif",
            "#ifndef R_386_JMP_SLOT",
            "#define R_386_JMP_SLOT 7",
            "#endif",
            "#ifndef R_386_RELATIVE",
            "#define R_386_RELATIVE 8",
            "#endif",
            "#ifndef R_386_GOTOFF",
            "#define R_386_GOTOFF 9",
            "#endif",
            "#ifndef R_386_GOTPC",
            "#define R_386_GOTPC 10",
            "#endif",
            "#ifndef R_386_16",
            "#define R_386_16 20",
            "#endif",
            "#ifndef R_386_PC16",
            "#define R_386_PC16 21",
            "#endif",
            "#ifndef R_386_8",
            "#define R_386_8 22",
            "#endif",
            "#ifndef R_386_PC8",
            "#define R_386_PC8 23",
            "#endif",
            "EOF",
            "cat $(location %s) >> $(location %s_x86_relocs_32.c)" % (source_label(source_repo, "arch/x86/tools/relocs.c"), target_prefix),
            "cat > $(location %s_x86_relocs_64.c) <<'EOF'" % target_prefix,
            "#include \"relocs.h\"",
            "#define ELF_BITS 64",
            "#define ELF_MACHINE EM_X86_64",
            "#define ELF_MACHINE_NAME \"x86_64\"",
            "#define SHT_REL_TYPE SHT_RELA",
            "#define Elf_Rel Elf64_Rela",
            "#define ELF_CLASS ELFCLASS64",
            "#define ELF_R_SYM(val) ELF64_R_SYM(val)",
            "#define ELF_R_TYPE(val) ELF64_R_TYPE(val)",
            "#define ELF_ST_TYPE(o) ELF64_ST_TYPE(o)",
            "#define ELF_ST_BIND(o) ELF64_ST_BIND(o)",
            "#define ELF_ST_VISIBILITY(o) ELF64_ST_VISIBILITY(o)",
            "#ifndef R_X86_64_NONE",
            "#define R_X86_64_NONE 0",
            "#endif",
            "#ifndef R_X86_64_64",
            "#define R_X86_64_64 1",
            "#endif",
            "#ifndef R_X86_64_PC32",
            "#define R_X86_64_PC32 2",
            "#endif",
            "#ifndef R_X86_64_GOT32",
            "#define R_X86_64_GOT32 3",
            "#endif",
            "#ifndef R_X86_64_PLT32",
            "#define R_X86_64_PLT32 4",
            "#endif",
            "#ifndef R_X86_64_COPY",
            "#define R_X86_64_COPY 5",
            "#endif",
            "#ifndef R_X86_64_GLOB_DAT",
            "#define R_X86_64_GLOB_DAT 6",
            "#endif",
            "#ifndef R_X86_64_JUMP_SLOT",
            "#define R_X86_64_JUMP_SLOT 7",
            "#endif",
            "#ifndef R_X86_64_RELATIVE",
            "#define R_X86_64_RELATIVE 8",
            "#endif",
            "#ifndef R_X86_64_GOTPCREL",
            "#define R_X86_64_GOTPCREL 9",
            "#endif",
            "#ifndef R_X86_64_32",
            "#define R_X86_64_32 10",
            "#endif",
            "#ifndef R_X86_64_32S",
            "#define R_X86_64_32S 11",
            "#endif",
            "#ifndef R_X86_64_16",
            "#define R_X86_64_16 12",
            "#endif",
            "#ifndef R_X86_64_PC16",
            "#define R_X86_64_PC16 13",
            "#endif",
            "#ifndef R_X86_64_8",
            "#define R_X86_64_8 14",
            "#endif",
            "#ifndef R_X86_64_PC8",
            "#define R_X86_64_PC8 15",
            "#endif",
            "#ifndef R_X86_64_PC64",
            "#define R_X86_64_PC64 24",
            "#endif",
            "EOF",
            "cat $(location %s) >> $(location %s_x86_relocs_64.c)" % (source_label(source_repo, "arch/x86/tools/relocs.c"), target_prefix),
        ]),
        visibility = visibility,
    )

    cc_binary(
        name = relocs_tool,
        srcs = [
            ":" + relocs_sources,
            source_label(source_repo, "arch/x86/tools/relocs_common.c"),
        ],
        visibility = visibility,
        deps = [
            Label("@libelf//:elf_headers"),
            source_label(source_repo, "tools_headers_cc"),
        ],
    )

    return struct(
        asn1_compiler = common.asn1_compiler,
        generated_headers = package_label(generated_headers),
        kallsyms_tool = common.kallsyms_tool,
        objtool = package_label(objtool),
        probe_config = common.probe_config,
        resolve_btfids_tool = common.resolve_btfids_tool,
        source_asn1_compiler = common.source_asn1_compiler,
        source_label_package = common.source_label_package,
        source_repo = source_repo,
        source_root = common.source_root,
        source_tree = common.source_tree,
        sorttable_tool = common.sorttable_tool,
        x86_relocs_tool = package_label(relocs_tool),
    )
