load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "nmrun_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/nmrun",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "nmrun",
    embed = [":nmrun_lib"],
    visibility = ["//:__subpackages__"],
)
