load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "versionheaders_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/versionheaders",
    visibility = ["//visibility:private"],
    deps = ["//internal/kconfig"],
)

go_binary(
    name = "versionheaders",
    embed = [":versionheaders_lib"],
    visibility = ["//:__subpackages__"],
)
