package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/hermeticbuild/linux.bzl/internal/kconfig"
)

func main() {
	configPath := flag.String("config", "", "Resolved Linux .config file")
	kernelReleasePath := flag.String("kernel_release", "", "include/config/kernel.release input")
	compileOut := flag.String("compile_out", "", "include/generated/compile.h output")
	linuxVersionOut := flag.String("linux_version_out", "", "include/generated/uapi/linux/version.h output")
	utsreleaseOut := flag.String("utsrelease_out", "", "include/generated/utsrelease.h output")
	utsversionOut := flag.String("utsversion_out", "", "UTS_VERSION header output")
	machine := flag.String("machine", "x86_64", "UTS_MACHINE value")
	compileBy := flag.String("compile_by", "bazel", "LINUX_COMPILE_BY value")
	compileHost := flag.String("compile_host", "bazel", "LINUX_COMPILE_HOST value")
	compiler := flag.String("compiler", "clang", "LINUX_COMPILER value")
	buildVersion := flag.String("build_version", "1", "KBUILD_BUILD_VERSION value")
	buildTimestamp := flag.String("build_timestamp", "1970-01-01T00:00:00Z", "KBUILD_BUILD_TIMESTAMP value")
	flag.Parse()

	if *configPath == "" || *kernelReleasePath == "" {
		flag.PrintDefaults()
		os.Exit(2)
	}
	if *compileOut == "" && *linuxVersionOut == "" && *utsreleaseOut == "" && *utsversionOut == "" {
		fmt.Fprintln(os.Stderr, "at least one output flag is required")
		os.Exit(2)
	}

	configFile, err := os.Open(*configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open config: %v\n", err)
		os.Exit(1)
	}
	config, err := kconfig.ParseConfig(configFile)
	closeErr := configFile.Close()
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse config: %v\n", err)
		os.Exit(1)
	}
	if closeErr != nil {
		fmt.Fprintf(os.Stderr, "close config: %v\n", closeErr)
		os.Exit(1)
	}

	releaseData, err := os.ReadFile(*kernelReleasePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read kernel release: %v\n", err)
		os.Exit(1)
	}
	release := strings.TrimSpace(string(releaseData))
	if release == "" {
		fmt.Fprintln(os.Stderr, "kernel release is empty")
		os.Exit(1)
	}

	if *compileOut != "" {
		if err := writeFile(*compileOut, compileHeader(*machine, *compileBy, *compileHost, *compiler)); err != nil {
			fmt.Fprintf(os.Stderr, "write compile header: %v\n", err)
			os.Exit(1)
		}
	}
	if *linuxVersionOut != "" {
		if err := writeFile(*linuxVersionOut, linuxVersionHeader(release)); err != nil {
			fmt.Fprintf(os.Stderr, "write linux version header: %v\n", err)
			os.Exit(1)
		}
	}
	if *utsreleaseOut != "" {
		if err := writeFile(*utsreleaseOut, utsreleaseHeader(release)); err != nil {
			fmt.Fprintf(os.Stderr, "write utsrelease header: %v\n", err)
			os.Exit(1)
		}
	}
	if *utsversionOut != "" {
		if err := writeFile(*utsversionOut, utsversionHeader(config, *buildVersion, *buildTimestamp)); err != nil {
			fmt.Fprintf(os.Stderr, "write utsversion header: %v\n", err)
			os.Exit(1)
		}
	}
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func compileHeader(machine, compileBy, compileHost, compiler string) string {
	var out strings.Builder
	fmt.Fprintln(&out, "/* Automatically generated by Bazel versionheaders. */")
	fmt.Fprintf(&out, "#define UTS_MACHINE\t\t%q\n", machine)
	fmt.Fprintf(&out, "#define LINUX_COMPILE_BY\t%q\n", compileBy)
	fmt.Fprintf(&out, "#define LINUX_COMPILE_HOST\t%q\n", compileHost)
	fmt.Fprintf(&out, "#define LINUX_COMPILER\t\t%q\n", compiler)
	return out.String()
}

func utsreleaseHeader(release string) string {
	return fmt.Sprintf("/* Automatically generated by Bazel versionheaders. */\n#define UTS_RELEASE %q\n", release)
}

func linuxVersionHeader(release string) string {
	major, patch, sublevel := kernelVersion(release)
	code := (major << 16) + (patch << 8)
	if sublevel > 255 {
		code += 255
	} else {
		code += sublevel
	}
	return fmt.Sprintf(`/* Automatically generated by Bazel versionheaders. */
#define LINUX_VERSION_MAJOR %d
#define LINUX_VERSION_PATCHLEVEL %d
#define LINUX_VERSION_SUBLEVEL %d
#define LINUX_VERSION_CODE %d
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + ((c) > 255 ? 255 : (c)))
`, major, patch, sublevel, code)
}

func kernelVersion(release string) (int, int, int) {
	parts := strings.SplitN(release, "-", 2)
	fields := strings.Split(parts[0], ".")
	values := [3]int{}
	for i := range values {
		if i >= len(fields) {
			continue
		}
		value, err := strconv.Atoi(fields[i])
		if err != nil {
			continue
		}
		values[i] = value
	}
	return values[0], values[1], values[2]
}

func utsversionHeader(config map[string]string, buildVersion, buildTimestamp string) string {
	parts := []string{"#" + buildVersion}
	if enabled(config, "CONFIG_SMP") {
		parts = append(parts, "SMP")
	}
	for _, key := range []string{"CONFIG_PREEMPT_BUILD", "CONFIG_PREEMPT_DYNAMIC", "CONFIG_PREEMPT_RT"} {
		if enabled(config, key) {
			parts = append(parts, strings.TrimPrefix(key, "CONFIG_"))
			break
		}
	}
	if buildTimestamp != "" {
		parts = append(parts, buildTimestamp)
	}
	value := strings.Join(parts, " ")
	if len(value) > 64 {
		value = value[:64]
	}
	return fmt.Sprintf("/* Automatically generated by Bazel versionheaders. */\n#define UTS_VERSION %q\n", value)
}

func enabled(config map[string]string, key string) bool {
	value := config[key]
	return value != "" && value != "n"
}
