load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "vdso2c_lib",
    srcs = ["main.go"],
    importpath = "linux.bzl/internal/cmd/vdso2c",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "vdso2c",
    embed = [":vdso2c_lib"],
    visibility = ["//:__subpackages__"],
)
