load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "vdso2c_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/vdso2c",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "vdso2c",
    embed = [":vdso2c_lib"],
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "vdso2c_test",
    srcs = ["main_test.go"],
    embed = [":vdso2c_lib"],
)
