load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "syscalltbl_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/syscalltbl",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "syscalltbl",
    embed = [":syscalltbl_lib"],
    visibility = ["//:__subpackages__"],
)
